const SV_POKEDEX_DATA = [
	{ id: "001", name: "Sprigatito", img: "sprigatito.gif", type1: "Grass", type2: "", location: "Starter", evolve: "" },
	{ id: "002", name: "Floragato", img: "floragato.gif", type1: "Grass", type2: "", location: "None", evolve: "Sprigatito (Lvl 16)" },
	{ id: "003", name: "Meowscarada", img: "meowscarada.gif", type1: "Grass", type2: "Dark", location: "None", evolve: "Floragato (Lvl 36)" },
	{ id: "004", name: "Fuecoco", img: "fuecoco.gif", type1: "Fire", type2: "", location: "Starter", evolve: "" },
	{ id: "005", name: "Crocalor", img: "crocalor.gif", type1: "Fire", type2: "", location: "None", evolve: "Fuecoco (Lvl 16)" },
	{ id: "006", name: "Skeledirge", img: "skeledirge.gif", type1: "Fire", type2: "Ghost", location: "None", evolve: "Crocalor (Lvl 36)" },
	{ id: "007", name: "Quaxly", img: "quaxly.gif", type1: "Water", type2: "", location: "Starter", evolve: "" },
	{ id: "008", name: "Quaxwell", img: "quaxwell.gif", type1: "Water", type2: "", location: "None", evolve: "Quaxly (Lvl 16)" },
	{ id: "009", name: "Quaquaval", img: "quaquaval.gif", type1: "Water", type2: "Fighting", location: "None", evolve: "Quaxwell (Lvl 36)" },
	{ id: "010", name: "Lechonk", img: "lechonk.gif", type1: "Normal", type2: "", location: "South 1 & 4 <span class='emoji-highlight'>🌱🌲</span>", evolve: "" },
	{ id: "011", name: "Oinkologne", img: "oinkologne.gif", type1: "Normal", type2: "", location: "East 1 & 2 <span class='emoji-highlight'>🌱🌲</span> <span class='percent'>20%</span>", evolve: "Lechonk (Lvl 18)" },
	{ id: "012", name: "Tarountula", img: "tarountula.gif", type1: "Bug", type2: "", location: "South 1 & 4 <span class='emoji-highlight'>🌱🌲</span>", evolve: "" },
	{ id: "013", name: "Spidops", img: "spidops.gif", type1: "Bug", type2: "", location: "East 1 & 2 <span class='emoji-highlight'>🌲🎋</span> <span class='percent'>20%</span>", evolve: "Tarountula (Lvl 15)" },
	{ id: "014", name: "Nymble", img: "nymble.gif", type1: "Bug", type2: "", location: "West 1 <span class='emoji-highlight'>🌱⛰️</span>", evolve: "" },
	{ id: "015", name: "Lokix", img: "lokix.gif", type1: "Bug", type2: "Dark", location: "West 1 <span class='emoji-highlight'>⛰️🪨🎋</span>", evolve: "Nymble (Lvl 24)" },
	{ id: "016", name: "Hoppip", img: "hoppip.gif", type1: "Grass", type2: "Flying", location: "South 1 & 2 <span class='emoji-highlight'>🌱</span>", evolve: "" },
	{ id: "017", name: "Skiploom", img: "skiploom.gif", type1: "Grass", type2: "Flying", location: "East 1 & 2 <span class='emoji-highlight'>🌱🌸</span> <span class='percent'>20%</span>", evolve: "Hoppip (Lvl 18)" },
	{ id: "018", name: "Jumpluff", img: "jumpluff.gif", type1: "Grass", type2: "Flying", location: "Great Crater <span class='emoji-highlight'>🌱</span>", evolve: "Skiploom (Lvl 27)" },
	{ id: "019", name: "Fletchling", img: "fletchling.gif", type1: "Normal", type2: "Flying", location: "South 1 & 2 <span class='emoji-highlight'>🌱</span>", evolve: "" },
	{ id: "020", name: "Fletchinder", img: "fletchinder.gif", type1: "Fire", type2: "Flying", location: "South 4 & 5 <span class='emoji-highlight'>🌱</span>", evolve: "Fletchling (Lvl 17)" },
	{ id: "021", name: "Talonflame", img: "talonflame.gif", type1: "Fire", type2: "Flying", location: "Great Crater <span class='emoji-highlight'>🪨</span>", evolve: "Fletchinder (Lvl 35)" },
	{ id: "022", name: "Pawmi", img: "pawmi.gif", type1: "Electric", type2: "", location: "South 1 & 3 <span class='emoji-highlight'>🌱🪨</span> <span class='percent'>5%</span>", evolve: "" },
	{ id: "023", name: "Pawmo", img: "pawmo.gif", type1: "Electric", type2: "Fighting", location: "South 2 & 4 <span class='emoji-highlight'>🌱⛰️</span> <span class='percent'>10%</span>", evolve: "Pawmi (Lvl 18)" },
	{ id: "024", name: "Pawmot", img: "pawmot.gif", type1: "Electric", type2: "Fighting", location: "None", evolve: "Pawmo (Walk 1000 Steps in LGPE)" },
	{ id: "025", name: "Houndour", img: "houndour.gif", type1: "Dark", type2: "Fire", location: "South 1 & 4 <span class='emoji-highlight'>🪨🦇</span>", evolve: "" },
	{ id: "026", name: "Houndoom", img: "houndoom.gif", type1: "Dark", type2: "Fire", location: "North 2 <span class='emoji-highlight'>🪨🦇</span> <span class='percent'>20%</span>", evolve: "Houndour (Lvl 24)" },
	{ id: "027", name: "Yungoos", img: "yungoos.gif", type1: "Normal", type2: "", location: "Any West <span class='emoji-highlight'>🦇</span>", evolve: "" },
	{ id: "028", name: "Gumshoos", img: "gumshoos.gif", type1: "Normal", type2: "", location: "Any West <span class='emoji-highlight'>🪨🦇</span>", evolve: "Yungoos (Lvl 20 during Day)" },
	{ id: "029", name: "Skwovet", img: "skwovet.gif", type1: "Normal", type2: "", location: "South 2 & 4 <span class='emoji-highlight'>🌲</span>", evolve: "" },
	{ id: "030", name: "Greedent", img: "greedent.gif", type1: "Normal", type2: "", location: "North 1 & 2 <span class='emoji-highlight'>🌲</span>", evolve: "Skwovet (Lvl 24)" },
	{ id: "031", name: "Sunkern", img: "sunkern.gif", type1: "Grass", type2: "", location: "South 1 & 2 <span class='emoji-highlight'>🌸</span><span class='time-highlight'>🌅🏙️🌇</span>", evolve: "" },
	{ id: "032", name: "Sunflora", img: "sunflora.gif", type1: "Grass", type2: "", location: "South 1 & 2 <span class='emoji-highlight'>🌸</span><span class='time-highlight'>🌅🏙️🌇</span>", evolve: "Sunkern (Sun Stone)" },
	{ id: "033", name: "Kricketot", img: "kricketot.gif", type1: "Bug", type2: "", location: "South 2 <span class='emoji-highlight'>🌿</span>", evolve: "" },
	{ id: "034", name: "Kricketune", img: "kricketune.gif", type1: "Bug", type2: "", location: "North 1 & 2 <span class='emoji-highlight'>🎋</span>", evolve: "Kricketot (Lvl 10)" },
	{ id: "035", name: "Scatterbug", img: "scatterbug.gif", type1: "Bug", type2: "", location: "South 1 <span class='emoji-highlight'>🌱</span>", evolve: "" },
	{ id: "036", name: "Spewpa", img: "spewpa.gif", type1: "Bug", type2: "", location: "South 1 & 4 <span class='emoji-highlight'>🌸</span>", evolve: "Scatterbug (Lvl 9)" },
	{ id: "037", name: "Vivillon", img: "vivillon.gif", type1: "Bug", type2: "Flying", location: "South 1 & 2 <span class='emoji-highlight'>🌸</span>", evolve: "Spewpa (Lvl 12)" },
	{ id: "038", name: "Combee", img: "combee.gif", type1: "Bug", type2: "Flying", location: "South 1 & 2 <span class='emoji-highlight'>🌸🌿</span>", evolve: "" },
	{ id: "039", name: "Vespiquen", img: "vespiquen.gif", type1: "Bug", type2: "Flying", location: "South 1 & 2 <span class='emoji-highlight'>🌸</span>", evolve: "Combee (Lvl 21 Female)" },
	{ id: "040", name: "Rookidee", img: "rookidee.gif", type1: "Flying", type2: "", location: "Any East <span class='emoji-highlight'>🌱⛰️🏡🪨</span>", evolve: "" },
	{ id: "041", name: "Corvisquire", img: "corvisquire.gif", type1: "Flying", type2: "", location: "Any East <span class='emoji-highlight'>🌱⛰️🏡🪨</span>", evolve: "Rookidee (Lvl 18)" },
	{ id: "042", name: "Corviknight", img: "corviknight.gif", type1: "Flying", type2: "Steel", location: "Great Crater <span class='emoji-highlight'>🌱</span> <span class='percent'>20%</span>", evolve: "Corvisquire (Lvl 38)" },
	{ id: "043", name: "Happiny", img: "happiny.gif", type1: "Normal", type2: "", location: "Any South <span class='emoji-highlight'>🌱🌸</span> <span class='percent'>1%</span>", evolve: "" },
	{ id: "044", name: "Chansey", img: "chansey.gif", type1: "Normal", type2: "", location: "North 3 <span class='emoji-highlight'>🌱🌸</span> <span class='percent'>1%</span>", evolve: "Happiny (Oval Stone)" },
	{ id: "045", name: "Blissey", img: "blissey.gif", type1: "Normal", type2: "", location: "Any North <span class='emoji-highlight'>🌸</span> <span class='percent'>1%</span>", evolve: "Chansey (High Friendship)" },
	{ id: "046", name: "Azurill", img: "azurill.gif", type1: "Normal", type2: "Fairy", location: "South 1 & 4 <span class='emoji-highlight'>⛵🎣</span>", evolve: "" },
	{ id: "047", name: "Marill", img: "marill.gif", type1: "Water", type2: "Fairy", location: "East 2 <span class='emoji-highlight'>🌱🏖️</span>", evolve: "Azurill (High Friendship)" },
	{ id: "048", name: "Azumarill", img: "azumarill.gif", type1: "Water", type2: "Fairy", location: "Casseroya Lake <span class='emoji-highlight'>⛵🎣</span>", evolve: "Marill (Lvl 18)" },
	{ id: "049", name: "Surskit", img: "surskit.gif", type1: "Bug", type2: "Water", location: "South 1 & 5 <span class='emoji-highlight'>⛵🎣</span>", evolve: "" },
	{ id: "050", name: "Masquerain", img: "masquerain.gif", type1: "Bug", type2: "Flying", location: "South 4 & 5 <span class='emoji-highlight'>⛵🎣</span> <span class='percent'>20%</span>", evolve: "Surskit (Lvl 22)" },
	{ id: "051", name: "Buizel", img: "buizel.gif", type1: "Water", type2: "", location: "East 1 & 2 <span class='emoji-highlight'>🎣🌊🏖️</span> <span class='percent'>20%</span>", evolve: "" },
	{ id: "052", name: "Floatzel", img: "floatzel.gif", type1: "Water", type2: "", location: "Any East <span class='emoji-highlight'>🌊</span>", evolve: "Buizel (Lvl 26)" },
	{ id: "053", name: "Paldean Wooper", img: "wooper-paldea.gif", type1: "Poison", type2: "Ground", location: "South 4 & 5 <span class='emoji-highlight'>⛵🪷</span>", evolve: "" },
	{ id: "054", name: "Clodsire", img: "clodsire.gif", type1: "Poison", type2: "Ground", location: "South 5 <span class='emoji-highlight'>⛵🪷</span>", evolve: "" },
	{ id: "055", name: "Psyduck", img: "psyduck.gif", type1: "Water", type2: "", location: "South 1 & 4 <span class='emoji-highlight'>⛵🎣</span>", evolve: "" },
	{ id: "056", name: "Golduck", img: "golduck.gif", type1: "Water", type2: "", location: "Casseroya Lake <span class='emoji-highlight'>⛵🎣</span> <span class='percent'>20%</span>", evolve: "Psyduck (Lvl 33)" },
	{ id: "057", name: "Chewtle", img: "chewtle.gif", type1: "Water", type2: "", location: "South 5 <span class='emoji-highlight'>🪷</span>", evolve: "" },
	{ id: "058", name: "Drednaw", img: "drednaw.gif", type1: "Water", type2: "Rock", location: "Casseroya Lake <span class='emoji-highlight'>⛵</span>", evolve: "Chewtle (Lvl 22)" },
	{ id: "059", name: "Igglybuff", img: "igglybuff.gif", type1: "Normal", type2: "Fairy", location: "South 1 & 2 <span class='emoji-highlight'>🏡</span>", evolve: "" },
	{ id: "060", name: "Jigglypuff", img: "jigglypuff.gif", type1: "Normal", type2: "Fairy", location: "West 3 <span class='emoji-highlight'>🏡</span>", evolve: "Igglybuff (High Friendship)" },
	{ id: "061", name: "Wigglytuff", img: "wigglytuff.gif", type1: "Normal", type2: "Fairy", location: "North 1 <span class='emoji-highlight'>⛰️</span> <span class='percent'>5%</span>", evolve: "Jigglypuff (Moon Stone)" },
	{ id: "062", name: "Ralts", img: "ralts.gif", type1: "Psychic", type2: "Fairy", location: "South 1 <span class='emoji-highlight'>🏡</span><span class='time-highlight'>🌅🏙️🌇</span>", evolve: "" },
	{ id: "063", name: "Kirlia", img: "kirlia.gif", type1: "Psychic", type2: "Fairy", location: "East 2 <span class='emoji-highlight'>🏡</span><span class='time-highlight'>🌅🏙️🌇</span>", evolve: "Ralts (Lvl 20)" },
	{ id: "064", name: "Gardevoir", img: "gardevoir.gif", type1: "Psychic", type2: "Fairy", location: "Glaseado Mountain <span class='emoji-highlight'>❄️</span><span class='time-highlight'>🌅🏙️🌇</span>", evolve: "Kirlia (Lvl 30)" },
	{ id: "065", name: "Gallade", img: "gallade.gif", type1: "Psychic", type2: "Fighting", location: "Glaseado Mountain <span class='emoji-highlight'>⛰️</span><span class='time-highlight'>🌅🏙️🌇</span>", evolve: "Kirlia (Dawn Stone on Male)" },
	{ id: "066", name: "Drowzee", img: "drowzee.gif", type1: "Psychic", type2: "", location: "South 1 & 2 <span class='emoji-highlight'>🏛️</span>", evolve: "" },
	{ id: "067", name: "Hypno", img: "hypno.gif", type1: "Psychic", type2: "", location: "Great Crater <span class='emoji-highlight'>🕳️</span>", evolve: "Drowzee (Lvl 26)" },
	{ id: "068", name: "Gastly", img: "gastly.gif", type1: "Ghost", type2: "Poison", location: "West 1 <span class='emoji-highlight'>⛰️</span><span class='time-highlight'>🌃</span>", evolve: "" },
	{ id: "069", name: "Haunter", img: "haunter.gif", type1: "Ghost", type2: "Poison", location: "Glaseado Mountain <span class='emoji-highlight'>⛰️❄️🏛️</span><span class='time-highlight'>🌃</span>", evolve: "Gastly (Lvl 25)" },
	{ id: "070", name: "Gengar", img: "gengar.gif", type1: "Ghost", type2: "Poison", location: "None", evolve: "Haunter (Trade)" },
	{ id: "071", name: "Tandemaus", img: "tandemaus.gif", type1: "Normal", type2: "", location: "Pokémon League <span class='emoji-highlight'>🏡</span>", evolve: "" },
	{ id: "072", name: "Maushold", img: "maushold.gif", type1: "Normal", type2: "", location: "None", evolve: "Tandemaus (Look Up Instructions)" },
	{ id: "073", name: "Pichu", img: "pichu.gif", type1: "Electric", type2: "", location: "South 1 & 2 <span class='emoji-highlight'>🌲</span> <span class='percent'>10%</span>", evolve: "" },
	{ id: "074", name: "Pikachu", img: "pikachu.gif", type1: "Electric", type2: "", location: "South 2 & 4 <span class='emoji-highlight'>🌲</span> <span class='percent'>10%</span>", evolve: "Pichu (High Friendship)" },
	{ id: "075", name: "Raichu", img: "raichu.gif", type1: "Electric", type2: "", location: "Casseroya Lake <span class='emoji-highlight'>🌱</span> <span class='percent'>10%</span>", evolve: "Pikachu (Thunder Stone)" },
	{ id: "076", name: "Fidough", img: "fidough.gif", type1: "Fairy", type2: "", location: "South 1 & 2 <span class='emoji-highlight'>🏡</span>", evolve: "" },
	{ id: "077", name: "Dachsbun", img: "dachsbun.gif", type1: "Fairy", type2: "", location: "South 1 & 2 <span class='emoji-highlight'>🏡</span>", evolve: "Fidough (Lvl 26)" },
	{ id: "078", name: "Slakoth", img: "slakoth.gif", type1: "Normal", type2: "", location: "South 3 & 5 <span class='emoji-highlight'>🌱</span> <span class='percent'>10%</span>", evolve: "" },
	{ id: "079", name: "Vigoroth", img: "vigoroth.gif", type1: "Normal", type2: "", location: "South 5 <span class='emoji-highlight'>🌱⛰️</span>", evolve: "Slakoth (Lvl 18)" },
	{ id: "080", name: "Slaking", img: "slaking.gif", type1: "Normal", type2: "", location: "Casseroya Lake <span class='emoji-highlight'>🌲</span> <span class='percent'>5%</span>", evolve: "Vigoroth (Lvl 36)" },
	{ id: "081", name: "Bounsweet", img: "bounsweet.gif", type1: "Grass", type2: "", location: "South 1 & 2 <span class='emoji-highlight'>🌲</span>", evolve: "" },
	{ id: "082", name: "Steenee", img: "steenee.gif", type1: "Grass", type2: "", location: "East 1 <span class='emoji-highlight'>🌲</span>", evolve: "Steenee (Lvl 18)" },
	{ id: "083", name: "Tsareena", img: "tsareena.gif", type1: "Grass", type2: "", location: "None", evolve: "Steenee (Lvl up w/ Stomp)" },
	{ id: "084", name: "Smoliv", img: "smoliv.gif", type1: "Grass", type2: "Normal", location: "South 2 <span class='emoji-highlight'>🌿</span>", evolve: "" },
	{ id: "085", name: "Dolliv", img: "dolliv.gif", type1: "Grass", type2: "Normal", location: "Any North <span class='emoji-highlight'>🌸</span> <span class='percent'>10%</span>", evolve: "Smoliv (Lvl 25)" },
	{ id: "086", name: "Arboliva", img: "arboliva.gif", type1: "Grass", type2: "Normal", location: "None", evolve: "Dolliv (Lvl 35)" },
	{ id: "087", name: "Bonsly", img: "bonsly.gif", type1: "Rock", type2: "", location: "South 1 & 2 <span class='emoji-highlight'>🌲</span>", evolve: "" },
	{ id: "088", name: "Sudowoodo", img: "sudowoodo.gif", type1: "Rock", type2: "", location: "Casseroya Lake <span class='emoji-highlight'>🌲</span>", evolve: "Bonsly (Lvl Up w/ Mimic)" },
	{ id: "089", name: "Rockruff", img: "rockruff.gif", type1: "Rock", type2: "", location: "West 1 <span class='emoji-highlight'>⛰️</span>", evolve: "" },
	{ id: "090", name: "Lycanroc", img: "lycanroc.gif", type1: "Rock", type2: "", location: "Great Crater <span class='emoji-highlight'>🪨🦇</span>", evolve: "Rockruff (Lvl 25)" },
	{ id: "091", name: "Rolycoly", img: "rolycoly.gif", type1: "Rock", type2: "", location: "East 3 <span class='emoji-highlight'>💎</span>", evolve: "" },
	{ id: "092", name: "Carkol", img: "carkol.gif", type1: "Rock", type2: "Fire", location: "East 3 <span class='emoji-highlight'>💎</span>", evolve: "Rolycoly (Lvl 18)" },
	{ id: "093", name: "Coalossal", img: "coalossal.gif", type1: "Rock", type2: "Fire", location: "None", evolve: "Carkol (Lvl 34)" },
	{ id: "094", name: "Shinx", img: "shinx.gif", type1: "Electric", type2: "", location: "South 3 <span class='emoji-highlight'>🪨</span>", evolve: "" },
	{ id: "095", name: "Luxio", img: "luxio.gif", type1: "Electric", type2: "", location: "South 5 <span class='emoji-highlight'>🌱</span> <span class='percent'>20%</span>", evolve: "Shinx (Lvl 15)" },
	{ id: "096", name: "Luxray", img: "luxray.gif", type1: "Electric", type2: "", location: "North 2 <span class='emoji-highlight'>🎋</span> <span class='percent'>20%</span>", evolve: "Luxio (Lvl 30)" },
	{ id: "097", name: "Starly", img: "starly.gif", type1: "Normal", type2: "Flying", location: "South 2 & 4 <span class='emoji-highlight'>🌱🌿</span> <span class='percent'>20%</span><span class='time-highlight'>🌅🏙️🌇</span>", evolve: "" },
	{ id: "098", name: "Staravia", img: "staravia.gif", type1: "Normal", type2: "Flying", location: "South 2 & 4 <span class='emoji-highlight'>🌱</span><span class='time-highlight'>🌅🏙️🌇</span>", evolve: "Starly (Lvl 14)" },
	{ id: "099", name: "Staraptor", img: "staraptor.gif", type1: "Normal", type2: "Flying", location: "Casseroya Lake <span class='emoji-highlight'>🌱⛵</span> <span class='percent'>7%</span><span class='time-highlight'>🌅🏙️🌇</span>", evolve: "Staravia (Lvl 34)" },
	{ id: "100", name: "Oricorio", img: "oricorio.gif", type1: "Fire", type2: "Flying", location: "East 1 <span class='emoji-highlight'>🏡🌸</span>", evolve: "" },
	{ id: "101", name: "Mareep", img: "mareep.gif", type1: "Electric", type2: "", location: "South 2 <span class='emoji-highlight'>🌱🌿</span>", evolve: "" },
	{ id: "102", name: "Flaaffy", img: "flaaffy.gif", type1: "Electric", type2: "", location: "West 2 <span class='emoji-highlight'>🌱</span>", evolve: "Mareep (Lvl 15)" },
	{ id: "103", name: "Ampharos", img: "ampharos.gif", type1: "Electric", type2: "", location: "North 1 <span class='emoji-highlight'>⛰️</span> <span class='percent'>1%</span>", evolve: "Flaaffy (Lvl 30)" },
	{ id: "104", name: "Petilil", img: "petilil.gif", type1: "Grass", type2: "", location: "South 2 & 4 <span class='emoji-highlight'>🌸</span>", evolve: "" },
	{ id: "105", name: "Lilligant", img: "lilligant.gif", type1: "Grass", type2: "", location: "North 3 <span class='emoji-highlight'>🌸</span> <span class='percent'>5%</span>", evolve: "Petilil (Sun Stone)" },
	{ id: "106", name: "Shroomish", img: "shroomish.gif", type1: "Grass", type2: "", location: "West 3 <span class='emoji-highlight'>🌱🌲</span>", evolve: "" },
	{ id: "107", name: "Breloom", img: "breloom.gif", type1: "Grass", type2: "Fighting", location: "West 3 <span class='emoji-highlight'>🌲🎋</span>", evolve: "Shroomish (Lvl 23)" },
	{ id: "108", name: "Applin", img: "applin.gif", type1: "Grass", type2: "Dragon", location: "North 1 & 2 <span class='emoji-highlight'>🌲</span> <span class='percent'>10%</span>", evolve: "" },
	{ id: "109", name: "Flapple", img: "flapple.gif", type1: "Grass", type2: "Dragon", location: "None", evolve: "Applin (Tart Apple)" },
	{ id: "110", name: "Appletun", img: "appletun.gif", type1: "Grass", type2: "Dragon", location: "None", evolve: "Applin (Sweet Apple)" },
	{ id: "111", name: "Spoink", img: "spoink.gif", type1: "Psychic", type2: "", location: "South 3 <span class='emoji-highlight'>⛰️🪨</span> <span class='percent'>20%</span>", evolve: "" },
	{ id: "112", name: "Grumpig", img: "grumpig.gif", type1: "Psychic", type2: "", location: "North 1 & 2 <span class='emoji-highlight'>⛰️🪨</span> <span class='percent'>20%</span>", evolve: "Spoink (Lvl 32)" },
	{ id: "113", name: "Squawkabilly", img: "squawkabilly.gif", type1: "Normal", type2: "Flying", location: "Any East <span class='emoji-highlight'>🏡</span>", evolve: "" },
	{ id: "114", name: "Misdreavus", img: "misdreavus.gif", type1: "Ghost", type2: "", location: "North 1 & 2 <span class='emoji-highlight'>⛵</span><span class='time-highlight'>🌃</span><span class='violet-highlight'>🟣only</span>", evolve: "" },
	{ id: "115", name: "Mismagius", img: "mismagius.gif", type1: "Ghost", type2: "", location: "Casseroya Lake <span class='emoji-highlight'>⛵</span> <span class='percent'>3%</span><span class='time-highlight'>🌃</span><span class='violet-highlight'>🟣only</span>", evolve: "Misdreavus (Dusk Stone)" },
	{ id: "116", name: "Makuhita", img: "makuhita.gif", type1: "Fighting", type2: "", location: "Any West <span class='emoji-highlight'>🪨🦇</span> <span class='percent'>20%</span>", evolve: "" },
	{ id: "117", name: "Hariyama", img: "hariyama.gif", type1: "Fighting", type2: "", location: "East 3 <span class='emoji-highlight'>💎</span>", evolve: "Makuhita (Lvl 24)" },
	{ id: "118", name: "Crabrawler", img: "crabrawler.gif", type1: "Fighting", type2: "", location: "North 1 & 3 <span class='emoji-highlight'>🏖️</span>", evolve: "" },
	{ id: "119", name: "Crabominable", img: "crabominable.gif", type1: "Fighting", type2: "Ice", location: "Glaseado Mountain <span class='emoji-highlight'>❄️</span> <span class='percent'>10%</span>", evolve: "Crabrawler (Ice Stone)" },
	{ id: "120", name: "Salandit", img: "salandit.gif", type1: "Poison", type2: "Fire", location: "North 1 <span class='emoji-highlight'>🦇</span>", evolve: "" },
	{ id: "121", name: "Salazzle", img: "salazzle.gif", type1: "Poison", type2: "Fire", location: "North 1 <span class='emoji-highlight'>🦇</span> <span class='percent'>5%</span>", evolve: "Salandit (Lvl 33 Female)" },
	{ id: "122", name: "Phanpy", img: "phanpy.gif", type1: "Ground", type2: "", location: "West 1 <span class='emoji-highlight'>🏜️⛰️⛵</span>", evolve: "" },
	{ id: "123", name: "Donphan", img: "donphan.gif", type1: "Ground", type2: "", location: "West 2 <span class='emoji-highlight'>🏜️🌱</span> <span class='percent'>20%</span>", evolve: "Phanpy (Lvl 25)" },
	{ id: "124", name: "Cufant", img: "cufant.gif", type1: "Steel", type2: "", location: "East 3 <span class='emoji-highlight'>💎</span>", evolve: "" },
	{ id: "125", name: "Copperajah", img: "copperajah.gif", type1: "Steel", type2: "", location: "East 3 <span class='emoji-highlight'>💎</span> <span class='percent'>15%</span>", evolve: "Cufant (Lvl 34)" },
	{ id: "126", name: "Gible", img: "gible.gif", type1: "Dragon", type2: "Ground", location: "West 1 & 2 <span class='emoji-highlight'>🦇</span>", evolve: "" },
	{ id: "127", name: "Gabite", img: "gabite.gif", type1: "Dragon", type2: "Ground", location: "Great Crater <span class='emoji-highlight'>🕳️</span>", evolve: "Gible (Lvl 24)" },
	{ id: "128", name: "Garchomp", img: "garchomp.gif", type1: "Dragon", type2: "Ground", location: "None", evolve: "Gabite (Lvl 48)" },
	{ id: "129", name: "Nacli", img: "nacli.gif", type1: "Rock", type2: "", location: "Any West <span class='emoji-highlight'>🪨</span>", evolve: "" },
	{ id: "130", name: "Naclstack", img: "naclstack.gif", type1: "Rock", type2: "", location: "Any North <span class='emoji-highlight'>🪨</span>", evolve: "Nacli (Lvl 24)" },
	{ id: "131", name: "Garganacl", img: "garganacl.gif", type1: "Rock", type2: "", location: "Great Crater <span class='emoji-highlight'>🕳️</span> <span class='percent'>20%</span>", evolve: "Naclstack (Lvl 38)" },
	{ id: "132", name: "Wingull", img: "wingull.gif", type1: "Water", type2: "Flying", location: "West 1 & 2 <span class='emoji-highlight'>🌊🏖️</span>", evolve: "" },
	{ id: "133", name: "Pelipper", img: "pelipper.gif", type1: "Water", type2: "Flying", location: "North Paldean Sea <span class='emoji-highlight'>🌊🏖️</span>", evolve: "Wingull (Lvl 25)" },
	{ id: "134", name: "Magikarp", img: "magikarp.gif", type1: "Water", type2: "", location: "South Paldean Sea <span class='emoji-highlight'>🌊🏖️</span>", evolve: "" },
	{ id: "135", name: "Gyarados", img: "gyarados.gif", type1: "Water", type2: "Flying", location: "Casseroya Lake <span class='emoji-highlight'>⛵</span> <span class='percent'>15%</span>", evolve: "Magikarp (Lvl 20)" },
	{ id: "136", name: "Arrokuda", img: "arrokuda.gif", type1: "Water", type2: "", location: "Any South <span class='emoji-highlight'>🎣🌊</span>", evolve: "" },
	{ id: "137", name: "Barraskewda", img: "barraskewda.gif", type1: "Water", type2: "", location: "Any North <span class='emoji-highlight'>🎣🌊</span> <span class='percent'>20%</span>", evolve: "Arrokuda (Lvl 26)" },
	{ id: "138", name: "Basculin", img: "basculin.gif", type1: "Water", type2: "", location: "Any West <span class='emoji-highlight'>⛵🎣</span>", evolve: "" },
	{ id: "139", name: "Gulpin", img: "gulpin.gif", type1: "Poison", type2: "", location: "East 1 <span class='emoji-highlight'>🌱🏡</span><span class='violet-highlight'>🟣only</span>", evolve: "" },
	{ id: "140", name: "Swalot", img: "swalot.gif", type1: "Poison", type2: "", location: "Casseroya Lake <span class='emoji-highlight'>⛵</span><span class='violet-highlight'>🟣only</span>", evolve: "Gulpin (Lvl 26)" },
	{ id: "141", name: "Meowth", img: "meowth.gif", type1: "Normal", type2: "", location: "West 2 & 3 <span class='emoji-highlight'>🌱🏡</span>", evolve: "" },
	{ id: "142", name: "Persian", img: "persian.gif", type1: "Normal", type2: "", location: "West 3 <span class='emoji-highlight'>🌱🏡</span>", evolve: "Meowth (Lvl 28)" },
	{ id: "143", name: "Drifloon", img: "drifloon.gif", type1: "Ghost", type2: "Flying", location: "South 2 & 6 <span class='emoji-highlight'>🏡⛰️</span><span class='time-highlight'>🌇🌃</span><span class='scarlet-highlight'>🔴only</span>", evolve: "" },
	{ id: "144", name: "Drifblim", img: "drifblim.gif", type1: "Ghost", type2: "Flying", location: "Glaseado Mountain <span class='emoji-highlight'>🏡⛰️</span> <span class='percent'>20%</span><span class='time-highlight'>🌇🌃</span><span class='scarlet-highlight'>🔴only</span>", evolve: "Drifloon (Lvl 28)" },
	{ id: "145", name: "Flabébé", img: "flabebe.gif", type1: "Fairy", type2: "", location: "South 4 & 6 <span class='emoji-highlight'>🌸</span>", evolve: "" },
	{ id: "146", name: "Floette", img: "floette.gif", type1: "Fairy", type2: "", location: "North 1 & 2 <span class='emoji-highlight'>🌸</span>", evolve: "Flabébé (Lvl 19)" },
	{ id: "147", name: "Florges", img: "florges.gif", type1: "Fairy", type2: "", location: "North 3 <span class='emoji-highlight'>🌸</span> <span class='percent'>1%</span>", evolve: "Floette (Shiny Stone)" },
	{ id: "148", name: "Diglett", img: "diglett.gif", type1: "Ground", type2: "", location: "East 3 <span class='emoji-highlight'>💎</span>", evolve: "" },
	{ id: "149", name: "Dugtrio", img: "dugtrio.gif", type1: "Ground", type2: "", location: "East 3 <span class='emoji-highlight'>💎</span>", evolve: "Diglett (Lvl 26)" },
	{ id: "150", name: "Torkoal", img: "torkoal.gif", type1: "Fire", type2: "", location: "East 3 <span class='emoji-highlight'>💎</span> <span class='percent'>10%</span>", evolve: "" },
	{ id: "151", name: "Numel", img: "numel.gif", type1: "Fire", type2: "Ground", location: "West 1 <span class='emoji-highlight'>⛰️</span>", evolve: "" },
	{ id: "152", name: "Camerupt", img: "camerupt.gif", type1: "Fire", type2: "Ground", location: "North 2 <span class='emoji-highlight'>🪨</span> <span class='percent'>20%</span>", evolve: "Numel (Lvl 33)" },
	{ id: "153", name: "Bronzor", img: "bronzor.gif", type1: "Steel", type2: "Psychic", location: "West 1 & 3 <span class='emoji-highlight'>🏛️</span>", evolve: "" },
	{ id: "154", name: "Bronzong", img: "bronzong.gif", type1: "Steel", type2: "Psychic", location: "Casseroya Lake <span class='emoji-highlight'>❄️🏛️</span>", evolve: "Bronzor (Lvl 33)" },
	{ id: "155", name: "Axew", img: "axew.gif", type1: "Dragon", type2: "", location: "North 1 <span class='emoji-highlight'>⛰️🎣</span> <span class='percent'>20%</span>", evolve: "" },
	{ id: "156", name: "Fraxure", img: "fraxure.gif", type1: "Dragon", type2: "", location: "Glaseado Mountain <span class='emoji-highlight'>⛰️</span> <span class='percent'>20%</span>", evolve: "Axew (Lvl 38)" },
	{ id: "157", name: "Haxorus", img: "haxorus.gif", type1: "Dragon", type2: "", location: "None", evolve: "Fraxure (Lvl 48)" },
	{ id: "158", name: "Mankey", img: "mankey.gif", type1: "Fighting", type2: "", location: "West 1 <span class='emoji-highlight'>🌱⛰️</span>", evolve: "" },
	{ id: "159", name: "Primeape", img: "primeape.gif", type1: "Fighting", type2: "", location: "North 1 & 2 <span class='emoji-highlight'>🌲🪨🎋</span> <span class='percent'>10%</span>", evolve: "Mankey (Lvl 28)" },
	{ id: "160", name: "Annihilape", img: "annihilape.gif", type1: "Fighting", type2: "Ghost", location: "None", evolve: "Primeape (Use Rage Fist x20)" },
	{ id: "161", name: "Meditite", img: "meditite.gif", type1: "Fighting", type2: "Psychic", location: "South 4 & 6 <span class='emoji-highlight'>⛰️🦇</span>", evolve: "" },
	{ id: "162", name: "Medicham", img: "medicham.gif", type1: "Fighting", type2: "Psychic", location: "South 6 <span class='emoji-highlight'> 🌱⛰️</span> <span class='percent'>20%</span>", evolve: "Meditite (Lvl 37)" },
	{ id: "163", name: "Riolu", img: "riolu.gif", type1: "Fighting", type2: "", location: "South 4 <span class='emoji-highlight'> ⛰️</span> <span class='percent'>20%</span>", evolve: "" },
	{ id: "164", name: "Lucario", img: "lucario.gif", type1: "Fighting", type2: "Steel", location: "North 1 & 2 <span class='emoji-highlight'> ⛰️🪨</span> <span class='percent'>3%</span>", evolve: "Riolu (High Friendship)" },
	{ id: "165", name: "Charcadet", img: "charcadet.gif", type1: "Fire", type2: "", location: "North 1 & 2 <span class='emoji-highlight'> 🌲⛰️🪨🦇</span> <span class='percent'>1%</span>", evolve: "" },
	{ id: "166", name: "Armarouge", img: "armarouge.gif", type1: "Fire", type2: "Psychic", location: "Evolve <span class='scarlet-highlight'>🔴only</span> or Trade", evolve: "Charcadet (Auspicious Armor)" },
	{ id: "167", name: "Ceruledge", img: "ceruledge.gif", type1: "Fire", type2: "Ghost", location: "Evolve <span class='violet-highlight'>🟣only</span> or Trade", evolve: "Armarouge (Malicious Armor)" },
	{ id: "168", name: "Barboach", img: "barboach.gif", type1: "Water", type2: "Ground", location: "South 1 & 4 <span class='emoji-highlight'>⛵</span>", evolve: "" },
	{ id: "169", name: "Whiscash", img: "whiscash.gif", type1: "Water", type2: "Ground", location: "South 1 & 4 <span class='emoji-highlight'>⛵</span> <span class='percent'>10%</span>", evolve: "Barboach (Lvl 30)" },
	{ id: "170", name: "Tadbulb", img: "tadbulb.gif", type1: "Electric", type2: "", location: "South 4 & 5 <span class='emoji-highlight'>🪷🎣</span>", evolve: "" },
	{ id: "171", name: "Bellibolt", img: "bellibolt.gif", type1: "Electric", type2: "", location: "Great Crater <span class='emoji-highlight'>🎣</span>", evolve: "Tadbulb (Thunder Stone)" },
	{ id: "172", name: "Goomy", img: "goomy.gif", type1: "Dragon", type2: "", location: "South 4 & 5 <span class='emoji-highlight'>🪷🎣</span>", evolve: "" },
	{ id: "173", name: "Sliggoo", img: "sliggoo.gif", type1: "Dragon", type2: "", location: "Casseroya Lake <span class='emoji-highlight'>🪷🎣</span>", evolve: "Goomy (Lvl 40)" },
	{ id: "174", name: "Goodra", img: "goodra.gif", type1: "Dragon", type2: "", location: "None", evolve: "Sliggoo (Lvl 50 While Raining)" },
	{ id: "175", name: "Croagunk", img: "croagunk.gif", type1: "Poison", type2: "Fighting", location: "South 5 <span class='emoji-highlight'>🪷⛵🎣</span>", evolve: "" },
	{ id: "176", name: "Toxicroak", img: "toxicroak.gif", type1: "Poison", type2: "Fighting", location: "Casseroya Lake <span class='emoji-highlight'>🪷⛵🎣</span>", evolve: "Croagunk (Lvl 37)" },
	{ id: "177", name: "Wattrel", img: "wattrel.gif", type1: "Electric", type2: "Flying", location: "South Paldean Sea <span class='emoji-highlight'>🌊🏖️</span>", evolve: "" },
	{ id: "178", name: "Kilowattrel", img: "kilowattrel.gif", type1: "Electric", type2: "Flying", location: "North Paldean Sea <span class='emoji-highlight'>🌊🏖️</span>", evolve: "Wattrel (Lvl 25)" },
	{ id: "179", name: "Eevee", img: "eevee.gif", type1: "Normal", type2: "", location: "West 3 <span class='emoji-highlight'>🏡</span>", evolve: "Breed any Eeveelution" },
	{ id: "180", name: "Vaporeon", img: "vaporeon.gif", type1: "Water", type2: "", location: "Casseroya Lake <span class='emoji-highlight'>⛵🎣</span> <span class='percent'>1%</span>", evolve: "Eevee (Water Stone)" },
	{ id: "181", name: "Jolteon", img: "jolteon.gif", type1: "Electric", type2: "", location: "West 3 <span class='emoji-highlight'>🌲</span> <span class='percent'>1%</span>", evolve: "Eevee (Thunder Stone)" },
	{ id: "182", name: "Flareon", img: "flareon.gif", type1: "Fire", type2: "", location: "North 1 <span class='emoji-highlight'>⛰️</span> <span class='percent'>1%</span>", evolve: "Eevee (Fire Stone)" },
	{ id: "183", name: "Espeon", img: "espeon.gif", type1: "Psychic", type2: "", location: "Any Area <span class='emoji-highlight'>🌱</span> <span class='percent'>1%</span><span class='time-highlight'>🌅🏙️🌇</span>", evolve: "Eevee (High Friendship During Day)" },
	{ id: "184", name: "Umbreon", img: "umbreon.gif", type1: "Dark", type2: "", location: "West 3 <span class='emoji-highlight'>🦇</span> <span class='percent'>1%</span><span class='time-highlight'>🌃</span>", evolve: "Eevee (High Friendship During Night)" },
	{ id: "185", name: "Leafeon", img: "leafeon.gif", type1: "Grass", type2: "", location: "West 3 <span class='emoji-highlight'>🌲</span> <span class='percent'>1%</span>", evolve: "Eevee (Leaf Stone)" },
	{ id: "186", name: "Glaceon", img: "glaceon.gif", type1: "Ice", type2: "", location: "Glaseado Mountain <span class='emoji-highlight'>❄️</span> <span class='percent'>1%</span>", evolve: "Eevee (Ice Stone)" },
	{ id: "187", name: "Sylveon", img: "sylveon.gif", type1: "Fairy", type2: "", location: "South 6 <span class='emoji-highlight'>🏡</span> <span class='percent'>1%</span>", evolve: "Eevee (Max Friendship w/ Fairy Move)" },
	{ id: "188", name: "Dunsparce", img: "dunsparce.gif", type1: "Normal", type2: "", location: "Great Crater <span class='emoji-highlight'>🕳️</span>", evolve: "" },
	{ id: "189", name: "Dudunsparce", img: "dudunsparce.gif", type1: "Normal", type2: "", location: "Great Crater <span class='emoji-highlight'>🕳️</span> <span class='percent'>2%</span>", evolve: "Dunsparce (Lvl Up w/ Hyper Drill)" },
	{ id: "190", name: "Deerling", img: "deerling.gif", type1: "Normal", type2: "Grass", location: "West 2 & 3 <span class='emoji-highlight'>🌱</span>", evolve: "" },
	{ id: "191", name: "Sawsbuck", img: "sawsbuck.gif", type1: "Normal", type2: "Grass", location: "West 2 & 3 <span class='emoji-highlight'>🌱🌲</span>", evolve: "Deerling (Lvl 34)" },
	{ id: "192", name: "Girafarig", img: "girafarig.gif", type1: "Normal", type2: "Psychic", location: "West 2 <span class='emoji-highlight'>🌱🌲</span>", evolve: "" },
	{ id: "193", name: "Farigiraf", img: "farigiraf.gif", type1: "Normal", type2: "Psychic", location: "Great Crater <span class='emoji-highlight'>🌱</span> <span class='percent'>10%</span>", evolve: "Girafarig (Lvl Up w/ Twin Beam)" },
	{ id: "194", name: "Grimer", img: "grimer.gif", type1: "Poison", type2: "", location: "East 2 <span class='emoji-highlight'>🏡</span>", evolve: "" },
	{ id: "195", name: "Muk", img: "muk.gif", type1: "Poison", type2: "", location: "East 2 <span class='emoji-highlight'>🏡</span> <span class='percent'>3%</span>", evolve: "Grimer (Lvl 38)" },
	{ id: "196", name: "Maschiff", img: "maschiff.gif", type1: "Dark", type2: "", location: "West 2 & 3 <span class='emoji-highlight'>🌱🏛️</span>", evolve: "" },
	{ id: "197", name: "Mabosstiff", img: "mabosstiff.gif", type1: "Dark", type2: "", location: "West 2 & 3 <span class='emoji-highlight'>🌱🌲🏛️</span>", evolve: "Maschiff (Lvl 30)" },
	{ id: "198", name: "Toxel", img: "toxel.gif", type1: "Electric", type2: "Poison", location: "South 4 & 6 <span class='emoji-highlight'>🌱⛰️🦇</span>", evolve: "" },
	{ id: "198", name: "Toxtricity", img: "toxtricity.gif", type1: "Electric", type2: "Poison", location: "South 4 & 6 <span class='emoji-highlight'>⛰️🦇</span> <span class='percent'>15%</span>", evolve: "Toxel (Lvl 30)" },
	{ id: "200", name: "Dedenne", img: "dedenne.gif", type1: "Electric", type2: "Fairy", location: "North 3 <span class='emoji-highlight'>🏡</span> <span class='percent'>20%</span>", evolve: "" },
	{ id: "201", name: "Pachirisu", img: "pachirisu.gif", type1: "Electric", type2: "", location: "South 4 & 5 <span class='emoji-highlight'>🌲</span>", evolve: "" },
	{ id: "202", name: "Shroodle", img: "shroodle.gif", type1: "Poison", type2: "Normal", location: "Tagtree Thicket <span class='emoji-highlight'>🌲</span>", evolve: "" },
	{ id: "203", name: "Grafaiai", img: "grafaiai.gif", type1: "Poison", type2: "Normal", location: "Tagtree Thicket <span class='emoji-highlight'>🌲</span>", evolve: "Shroodle (Lvl 28)" },
	{ id: "204", name: "Stantler", img: "stantler.gif", type1: "Normal", type2: "", location: "South 5 <span class='emoji-highlight'>🌱🪨</span>", evolve: "" },
	{ id: "205", name: "Foongus", img: "foongus.gif", type1: "Grass", type2: "Poison", location: "East 1 & 2 <span class='emoji-highlight'>🌲</span>", evolve: "" },
	{ id: "206", name: "Amoonguss", img: "amoonguss.gif", type1: "Grass", type2: "Poison", location: "East 1 & 2 <span class='emoji-highlight'>🌲</span>", evolve: "Foongus (Lvl 39)" },
	{ id: "207", name: "Voltorb", img: "voltorb.gif", type1: "Electric", type2: "", location: "West 3 <span class='emoji-highlight'>🏡💎</span>", evolve: "" },
	{ id: "208", name: "Electrode", img: "electrode.gif", type1: "Electric", type2: "", location: "West 3 <span class='emoji-highlight'>🏡</span> <span class='percent'>10%</span>", evolve: "Voltorb (Lvl 30)" },
	{ id: "209", name: "Magnemite", img: "magnemite.gif", type1: "Electric", type2: "Steel", location: "East 2 & 3 <span class='emoji-highlight'>🌱</span>", evolve: "" },
	{ id: "210", name: "Magneton", img: "magneton.gif", type1: "Electric", type2: "Steel", location: "Glaseado Mountain <span class='emoji-highlight'>⛰️</span> <span class='percent'>20%</span>", evolve: "Magnemite (Lvl 30)" },
	{ id: "211", name: "Magnezone", img: "magnezone.gif", type1: "Electric", type2: "Steel", location: "None", evolve: "Magneton (Thunder Stone)" },
	{ id: "212", name: "Ditto", img: "ditto.gif", type1: "Normal", type2: "", location: "West 2 & 3 <span class='emoji-highlight'>🏡</span>", evolve: "" },
	{ id: "213", name: "Growlithe", img: "growlithe.gif", type1: "Fire", type2: "", location: "East 3 <span class='emoji-highlight'>🪨💎</span> <span class='percent'>10%</span>", evolve: "" },
	{ id: "214", name: "Arcanine", img: "arcanine.gif", type1: "Fire", type2: "", location: "North 2 <span class='emoji-highlight'>🪨🎋</span> <span class='percent'>2%</span>", evolve: "Growlithe (Fire Stone)" },
	{ id: "215", name: "Teddiursa", img: "teddiursa.gif", type1: "Normal", type2: "", location: "East 1 <span class='emoji-highlight'>🌲</span>", evolve: "" },
	{ id: "216", name: "Ursaring", img: "ursaring.gif", type1: "Normal", type2: "", location: "North 1 & 2 <span class='emoji-highlight'>🌲⛰️🎋</span>", evolve: "Teddiursa (Lvl 30)" },
	{ id: "217", name: "Zangoose", img: "zangoose.gif", type1: "Normal", type2: "", location: "South 5 <span class='emoji-highlight'>⛵</span>", evolve: "" },
	{ id: "218", name: "Seviper", img: "seviper.gif", type1: "Poison", type2: "", location: "South 5 <span class='emoji-highlight'>🌱⛵</span> <span class='percent'>15%</span>", evolve: "" },
	{ id: "219", name: "Swablu", img: "swablu.gif", type1: "Normal", type2: "Flying", location: "West 1 <span class='emoji-highlight'>⛰️</span>", evolve: "" },
	{ id: "220", name: "Altaria", img: "altaria.gif", type1: "Dragon", type2: "Flying", location: "Great Crater <span class='emoji-highlight'>🎣</span>", evolve: "Swablu (Lvl 35)" },
	{ id: "221", name: "Skiddo", img: "skiddo.gif", type1: "Grass", type2: "", location: "Any West <span class='emoji-highlight'>⛰️🪨</span>", evolve: "" },
	{ id: "222", name: "Gogoat", img: "gogoat.gif", type1: "Grass", type2: "", location: "Any North <span class='emoji-highlight'>⛰️🪨</span>", evolve: "Skiddo (Lvl 32)" },
	{ id: "223", name: "Tauros", img: "tauros.gif", type1: "Normal", type2: "", location: "East 1 & 2 <span class='emoji-highlight'>🌱</span>", evolve: "" },
	{ id: "224", name: "Litleo", img: "litleo.gif", type1: "Fire", type2: "Normal", location: "East 1 <span class='emoji-highlight'>🌱⛰️🪨</span>", evolve: "" },
	{ id: "225", name: "Pyroar", img: "pyroar.gif", type1: "Fire", type2: "Normal", location: "Glaseado Mountain <span class='emoji-highlight'>🌱⛰️🪨</span>", evolve: "Litleo (Lvl 35)" },
	{ id: "226", name: "Stunky", img: "stunky.gif", type1: "Poison", type2: "Dark", location: "West 2 <span class='emoji-highlight'>🌱⛵</span><span class='scarlet-highlight'>🔴only</span>", evolve: "" },
	{ id: "227", name: "Skuntank", img: "skuntank.gif", type1: "Poison", type2: "Dark", location: "Casseroya Lake <span class='emoji-highlight'>🌲⛵</span><span class='scarlet-highlight'>🔴only</span>", evolve: "Stunky (Lvl 34)" },
	{ id: "228", name: "Zorua", img: "zorua.gif", type1: "Dark", type2: "", location: "Tagtree Thicket <span class='emoji-highlight'>🌲</span>", evolve: "" },
	{ id: "229", name: "Zoroark", img: "zoroark.gif", type1: "Dark", type2: "", location: "Tagtree Thicket <span class='emoji-highlight'>🌲</span> <span class='percent'>10%</span>", evolve: "Zorua (Lvl 30)" },
	{ id: "230", name: "Sneasel", img: "sneasel.gif", type1: "Dark", type2: "Ice", location: "North 1 <span class='emoji-highlight'>⛰️❄️</span>", evolve: "" },
	{ id: "231", name: "Weavile", img: "weavile.gif", type1: "Dark", type2: "Ice", location: "North 1 <span class='emoji-highlight'>❄️</span> <span class='percent'>1%</span>", evolve: "Sneasel (Level Up w/ Razor Claw at Night)" },
	{ id: "232", name: "Murkrow", img: "murkrow.gif", type1: "Dark", type2: "Flying", location: "Any East <span class='emoji-highlight'>🌱🏡</span><span class='time-highlight'>🌇🌃</span>", evolve: "" },
	{ id: "233", name: "Honchkrow", img: "honchkrow.gif", type1: "Dark", type2: "Flying", location: "South 2 & 4 <span class='emoji-highlight'>🌲⛰️🪨</span> <span class='percent'>1%</span><span class='time-highlight'>🌇🌃</span>", evolve: "Murkrow (Dusk Stone)" },
	{ id: "234", name: "Gothita", img: "gothita.gif", type1: "Psychic", type2: "", location: "Glaseado Mountain <span class='emoji-highlight'>🏡</span>", evolve: "" },
	{ id: "235", name: "Gothorita", img: "gothorita.gif", type1: "Psychic", type2: "", location: "South 6 <span class='emoji-highlight'>🏡</span>", evolve: "Gothita (Lvl 32)" },
	{ id: "236", name: "Gothitelle", img: "gothitelle.gif", type1: "Psychic", type2: "", location: "South 6 <span class='emoji-highlight'>🏡</span> <span class='percent'>1%</span>", evolve: "Gothorita (Lvl 41)" },
	{ id: "237", name: "Sinistea", img: "sinistea.gif", type1: "Ghost", type2: "", location: "East 3 <span class='emoji-highlight'>🏡🏛️</span>", evolve: "" },
	{ id: "238", name: "Polteageist", img: "polteageist.gif", type1: "Ghost", type2: "", location: "None", evolve: "Sinistea (Cracked Pot)" },
	{ id: "239", name: "Mimikyu", img: "mimikyu.gif", type1: "Ghost", type2: "Fairy", location: "Glaseado Mountain <span class='emoji-highlight'>🏛️</span>", evolve: "" },
	{ id: "240", name: "Klefki", img: "klefki.gif", type1: "Steel", type2: "Fairy", location: "Glaseado Mountain <span class='emoji-highlight'>🏡</span>", evolve: "" },
	{ id: "241", name: "Indeedee", img: "indeedee.gif", type1: "Psychic", type2: "Normal", location: "North 1 & 2 <span class='emoji-highlight'>🌱⛰️</span>", evolve: "" },
	{ id: "242", name: "Bramblin", img: "bramblin.gif", type1: "Grass", type2: "Ghost", location: "Asado Desert <span class='emoji-highlight'>🏜️</span>", evolve: "" },
	{ id: "243", name: "Brambleghast", img: "brambleghast.gif", type1: "Grass", type2: "Ghost", location: "North 1 <span class='emoji-highlight'>🌲⛰️</span> <span class='percent'>1%</span>", evolve: "Bramblin (Walk 1000 steps in LGPE)" },
	{ id: "244", name: "Toedscool", img: "toedscool.gif", type1: "Ground", type2: "Grass", location: "Any East <span class='emoji-highlight'>🌲</span>", evolve: "" },
	{ id: "245", name: "Toedscruel", img: "toedscruel.gif", type1: "Ground", type2: "Grass", location: "Casseroya Lake <span class='emoji-highlight'>🌲</span> <span class='percent'>5%</span>", evolve: "Toedscool (Lvl 30)" },
	{ id: "246", name: "Tropius", img: "tropius.gif", type1: "Grass", type2: "Flying", location: "Casseroya Lake <span class='emoji-highlight'>🌲⛵</span>", evolve: "" },
	{ id: "247", name: "Fomantis", img: "fomantis.gif", type1: "Grass", type2: "", location: "North 1 & 2 <span class='emoji-highlight'>🌸</span>", evolve: "" },
	{ id: "248", name: "Lurantis", img: "lurantis.gif", type1: "Grass", type2: "", location: "North 1 & 2 <span class='emoji-highlight'>🌸</span>", evolve: "Fomantis (Lvl 34 at Day)" },
	{ id: "249", name: "Klawf", img: "klawf.gif", type1: "Rock", type2: "", location: "South 3 <span class='emoji-highlight'>🪨</span>", evolve: "" },
	{ id: "250", name: "Capsakid", img: "capsakid.gif", type1: "Grass", type2: "", location: "Asado Desert <span class='emoji-highlight'>🏜️</span>", evolve: "" },
	{ id: "251", name: "Scovillain", img: "scovillain.gif", type1: "Grass", type2: "Fire", location: "North 1 <span class='emoji-highlight'>⛰️</span> <span class='percent'>10%</span>", evolve: "Capsakid (Fire Stone)" },
	{ id: "252", name: "Cacnea", img: "cacnea.gif", type1: "Grass", type2: "", location: "Asado Desert <span class='emoji-highlight'>🏜️</span>", evolve: "" },
	{ id: "253", name: "Cacturne", img: "cacturne.gif", type1: "Grass", type2: "Dark", location: "Asado Desert <span class='emoji-highlight'>🏜️</span> <span class='percent'>20%</span>", evolve: "Cacnea (Lvl 32)" },
	{ id: "254", name: "Rellor", img: "rellor.gif", type1: "Bug", type2: "", location: "Asado Desert <span class='emoji-highlight'>🏜️</span>", evolve: "" },
	{ id: "255", name: "Rabsca", img: "rabsca.gif", type1: "Bug", type2: "Psychic", location: "Asado Desert <span class='emoji-highlight'>🏜️</span> <span class='percent'>1%</span>", evolve: "Rellor (Walk 1000 steps in LGPE)" },
	{ id: "256", name: "Venonat", img: "venonat.gif", type1: "Bug", type2: "Poison", location: "East 1 & 2 <span class='emoji-highlight'>🌲</span>", evolve: "" },
	{ id: "257", name: "Venomoth", img: "venomoth.gif", type1: "Bug", type2: "Poison", location: "North 1 & 2 <span class='emoji-highlight'>🌲</span><span class='time-highlight'>🌃</span>", evolve: "Venonat (Lvl 31)" },
	{ id: "258", name: "Pineco", img: "pineco.gif", type1: "Bug", type2: "", location: "North 1 & 2 <span class='emoji-highlight'>🌲</span>", evolve: "" },
	{ id: "259", name: "Forretress", img: "forretress.gif", type1: "Bug", type2: "Steel", location: "Casseroya Lake <span class='emoji-highlight'>🌲</span> <span class='percent'>20%</span>", evolve: "Pineco (Lvl 31)" },
	{ id: "260", name: "Scyther", img: "scyther.gif", type1: "Bug", type2: "Flying", location: "Casseroya Lake <span class='emoji-highlight'>⛵🎋</span>", evolve: "" },
	{ id: "261", name: "Scizor", img: "scizor.gif", type1: "Bug", type2: "Steel", location: "None", evolve: "Scyther (Trade holding Metal Coat)" },
	{ id: "262", name: "Heracross", img: "heracross.gif", type1: "Bug", type2: "Fighting", location: "Casseroya Lake <span class='emoji-highlight'>🌲</span>", evolve: "" },
	{ id: "263", name: "Flittle", img: "flittle.gif", type1: "Psychic", type2: "", location: "Asado Desert <span class='emoji-highlight'>🏜️</span>", evolve: "" },
	{ id: "264", name: "Espathra", img: "espathra.gif", type1: "Psychic", type2: "", location: "North 1 <span class='emoji-highlight'>⛰️</span>", evolve: "Flittle (Lvl 35)" },
	{ id: "265", name: "Hippopotas", img: "hippopotas.gif", type1: "Ground", type2: "", location: "Asado Desert <span class='emoji-highlight'>🏜️</span>", evolve: "" },
	{ id: "266", name: "Hippowdon", img: "hippowdon.gif", type1: "Ground", type2: "", location: "Asado Desert <span class='emoji-highlight'>🏜️</span>", evolve: "Hippopotas (Lvl 34)" },
	{ id: "267", name: "Sandile", img: "sandile.gif", type1: "Ground", type2: "Dark", location: "Asado Desert <span class='emoji-highlight'>🏜️</span>", evolve: "" },
	{ id: "268", name: "Krokorok", img: "krokorok.gif", type1: "Ground", type2: "Dark", location: "Asado Desert <span class='emoji-highlight'>🏜️</span>", evolve: "Sandile (Lvl 29)" },
	{ id: "269", name: "Krookodile", img: "krookodile.gif", type1: "Ground", type2: "Dark", location: "None", evolve: "Krokorok (Lvl 40)" },
	{ id: "270", name: "Silicobra", img: "silicobra.gif", type1: "Ground", type2: "", location: "Asado Desert <span class='emoji-highlight'>🏜️</span>", evolve: "" },
	{ id: "271", name: "Sandaconda", img: "sandaconda.gif", type1: "Ground", type2: "", location: "Asado Desert <span class='emoji-highlight'>🏜️</span>", evolve: "Silicobra (Lvl 36)" },
	{ id: "272", name: "Mudbray", img: "mudbray.gif", type1: "Ground", type2: "", location: "West 1 <span class='emoji-highlight'>⛰️</span>", evolve: "" },
	{ id: "273", name: "Mudsdale", img: "mudsdale.gif", type1: "Ground", type2: "", location: "North 1 <span class='emoji-highlight'>⛰️</span> <span class='percent'>12%</span>", evolve: "Mudbray (Lvl 30)" },
	{ id: "274", name: "Larvesta", img: "larvesta.gif", type1: "Bug", type2: "Fire", location: "Asado Desert <span class='emoji-highlight'>🏜️</span> <span class='percent'>5%</span>", evolve: "" },
	{ id: "275", name: "Volcarona", img: "volcarona.gif", type1: "Bug", type2: "Fire", location: "Great Crater <span class='emoji-highlight'>🌱</span> <span class='percent'>1%</span>", evolve: "Larvesta (Lvl 59)" },
	{ id: "276", name: "Bagon", img: "bagon.gif", type1: "Dragon", type2: "", location: "South 5 <span class='emoji-highlight'>⛰️</span><span class='violet-highlight'>🟣only</span>", evolve: "" },
	{ id: "277", name: "Shelgon", img: "shelgon.gif", type1: "Dragon", type2: "", location: "South 6 <span class='emoji-highlight'>🦇</span> <span class='percent'>10%</span><span class='violet-highlight'>🟣only</span>", evolve: "Bagon (Lvl 30)" },
	{ id: "278", name: "Salamence", img: "salamence.gif", type1: "Dragon", type2: "Flying", location: "None", evolve: "Shelgon (Lvl 50)" },
	{ id: "279", name: "Tinkatink", img: "tinkatink.gif", type1: "Fairy", type2: "Steel", location: "Any South <span class='emoji-highlight'>🏛️</span>", evolve: "" },
	{ id: "280", name: "Tinkatuff", img: "tinkatuff.gif", type1: "Fairy", type2: "Steel", location: "North 1 & 2 <span class='emoji-highlight'>⛰️</span>", evolve: "Tinkatink (Lvl 24)" },
	{ id: "281", name: "Tinkaton", img: "tinkaton.gif", type1: "Fairy", type2: "Steel", location: "None", evolve: "Tinkatuff (Lvl 38)" },
	{ id: "282", name: "Hatenna", img: "hatenna.gif", type1: "Psychic", type2: "", location: "West 3 <span class='emoji-highlight'>⛵</span>", evolve: "" },
	{ id: "283", name: "Hattrem", img: "hattrem.gif", type1: "Psychic", type2: "", location: "North 1 & 2 <span class='emoji-highlight'>⛵</span>", evolve: "Hatenna (Lvl 32)" },
	{ id: "284", name: "Hatterene", img: "hatterene.gif", type1: "Psychic", type2: "Fairy", location: "None", evolve: "Hattrem (Lvl 42)" },
	{ id: "285", name: "Impidimp", img: "impidimp.gif", type1: "Dark", type2: "Fairy", location: "Tagtree Thicket <span class='emoji-highlight'>🌲</span>", evolve: "" },
	{ id: "286", name: "Morgrem", img: "morgrem.gif", type1: "Dark", type2: "Fairy", location: "Tagtree Thicket <span class='emoji-highlight'>🌲</span> <span class='percent'>20%</span>", evolve: "Impidimp (Lvl 32)" },
	{ id: "287", name: "Grimmsnarl", img: "grimmsnarl.gif", type1: "Dark", type2: "Fairy", location: "None", evolve: "Morgrem (Lvl 42)" },
	{ id: "288", name: "Wiglett", img: "wiglett.gif", type1: "Water", type2: "", location: "East 1 & 2 <span class='emoji-highlight'>🏖️</span>", evolve: "" },
	{ id: "289", name: "Wugtrio", img: "wugtrio.gif", type1: "Water", type2: "", location: "North 1 & 3 <span class='emoji-highlight'>🏖️</span> <span class='percent'>20%</span>", evolve: "Wiglett (Lvl 26)" },
	{ id: "290", name: "Bombirdier", img: "bombirdier.gif", type1: "Flying", type2: "Dark", location: "West 1 & 2 <span class='emoji-highlight'>🏖️</span>", evolve: "" },
	{ id: "291", name: "Finizen", img: "finizen.gif", type1: "Water", type2: "", location: "Any East <span class='emoji-highlight'>🌊</span>", evolve: "" },
	{ id: "292", name: "Palafin", img: "palafin.gif", type1: "Water", type2: "", location: "None", evolve: "Finizen (Lvl 38 in Co-op)" },
	{ id: "293", name: "Varoom", img: "varoom.gif", type1: "Steel", type2: "Poison", location: "East 3 <span class='emoji-highlight'>🏡💎</span> <span class='percent'>10%</span>", evolve: "" },
	{ id: "294", name: "Revavroom", img: "revavroom.gif", type1: "Steel", type2: "Poison", location: "East 3 <span class='emoji-highlight'>🪨</span>", evolve: "Varoom (Lvl 40)" },
	{ id: "295", name: "Cyclizar", img: "cyclizar.gif", type1: "Dragon", type2: "Normal", location: "East 2 <span class='emoji-highlight'>🌱🌲⛰️🎣</span> <span class='percent'>1%</span>", evolve: "" },
	{ id: "296", name: "Orthworm", img: "orthworm.gif", type1: "Steel", type2: "", location: "East 3 <span class='emoji-highlight'>💎</span>", evolve: "" },
	{ id: "297", name: "Sableye", img: "sableye.gif", type1: "Dark", type2: "Ghost", location: "Any West <span class='emoji-highlight'>🦇</span> <span class='percent'>20%</span>", evolve: "" },
	{ id: "298", name: "Shuppet", img: "shuppet.gif", type1: "Ghost", type2: "", location: "Any East <span class='emoji-highlight'>🏡</span><span class='time-highlight'>🌃</span>", evolve: "" },
	{ id: "299", name: "Banette", img: "banette.gif", type1: "Ghost", type2: "", location: "Glaseado Mountain <span class='emoji-highlight'>🏡</span><span class='time-highlight'>🌃</span>", evolve: "Shuppet (Lvl 37)" },
	{ id: "300", name: "Falinks", img: "falinks.gif", type1: "Fighting", type2: "", location: "North 2 <span class='emoji-highlight'>🎋🏛️</span>", evolve: "" },
	{ id: "301", name: "Hawlucha", img: "hawlucha.gif", type1: "Fighting", type2: "Flying", location: "North 1 & 2 <span class='emoji-highlight'>⛰️🪨</span>", evolve: "" },
	{ id: "302", name: "Spiritomb", img: "spiritomb.gif", type1: "Ghost", type2: "Dark", location: "Glaseado Mountain <span class='emoji-highlight'>⛰️</span> <span class='percent'>1%</span><span class='time-highlight'>🌃</span>", evolve: "" },
	{ id: "303", name: "Noibat", img: "noibat.gif", type1: "Flying", type2: "Dragon", location: "North 1 & 2 <span class='emoji-highlight'>🦇</span>", evolve: "" },
	{ id: "304", name: "Noivern", img: "noivern.gif", type1: "Flying", type2: "Dragon", location: "North 1 & 2 <span class='emoji-highlight'>🦇🪨</span>", evolve: "Noibat (Lvl 48)" },
	{ id: "305", name: "Dreepy", img: "dreepy.gif", type1: "Dragon", type2: "Ghost", location: "South 5 <span class='emoji-highlight'>🪷</span> <span class='percent'>20%</span><span class='violet-highlight'>🟣only</span>", evolve: "" },
	{ id: "306", name: "Drakloak", img: "drakloak.gif", type1: "Dragon", type2: "Ghost", location: "Casseroya Lake <span class='emoji-highlight'>⛵</span><span class='violet-highlight'>🟣only</span>", evolve: "Dreepy (Lvl 50)" },
	{ id: "307", name: "Dragapult", img: "dragapult.gif", type1: "Dragon", type2: "Ghost", location: "None", evolve: "Drakloak (Lvl 60)" },
	{ id: "308", name: "Glimmet", img: "glimmet.gif", type1: "Rock", type2: "Poison", location: "Great Crater <span class='emoji-highlight'>🕳️</span>", evolve: "" },
	{ id: "309", name: "Glimmora", img: "glimmora.gif", type1: "Rock", type2: "Poison", location: "Great Crater <span class='emoji-highlight'>🕳️</span>", evolve: "Glimmet (Lvl 35)" },
	{ id: "310", name: "Rotom", img: "rotom.gif", type1: "Electric", type2: "Ghost", location: "East 2 <span class='emoji-highlight'>🏡</span> <span class='percent'>10%</span>", evolve: "" },
	{ id: "311", name: "Greavard", img: "greavard.gif", type1: "Ghost", type2: "", location: "Glaseado Mountain <span class='emoji-highlight'>⛰️❄️🏛️</span>", evolve: "" },
	{ id: "312", name: "Houndstone", img: "houndstone.gif", type1: "Ghost", type2: "", location: "Glaseado Mountain <span class='emoji-highlight'>⛰️❄️🏛️</span> <span class='percent'>10%</span>", evolve: "Greavard (Lvl 30 at night)" },
	{ id: "313", name: "Oranguru", img: "oranguru.gif", type1: "Normal", type2: "Psychic", location: "North 2 <span class='emoji-highlight'>🌲🎋</span> <span class='percent'>15%</span><span class='scarlet-highlight'>🔴only</span>", evolve: "" },
	{ id: "314", name: "Passimian", img: "passimian.gif", type1: "Fighting", type2: "", location: "North 2 <span class='emoji-highlight'>🌲🎋</span> <span class='percent'>15%</span><span class='violet-highlight'>🟣only</span>", evolve: "" },
	{ id: "315", name: "Komala", img: "komala.gif", type1: "Normal", type2: "", location: "North 1 & 2 <span class='emoji-highlight'>🌲</span>", evolve: "" },
	{ id: "316", name: "Larvitar", img: "larvitar.gif", type1: "Rock", type2: "Ground", location: "South 5 <span class='emoji-highlight'>⛰️</span><span class='scarlet-highlight'>🔴only</span>", evolve: "" },
	{ id: "317", name: "Pupitar", img: "pupitar.gif", type1: "Rock", type2: "Ground", location: "South 6 <span class='emoji-highlight'>🦇</span><span class='scarlet-highlight'>🔴only</span>", evolve: "Larvitar (Lvl 30)" },
	{ id: "318", name: "Tyranitar", img: "tyranitar.gif", type1: "Rock", type2: "Dark", location: "None", evolve: "Pupitar (Lvl 55)" },
	{ id: "319", name: "Stonjourner", img: "stonjourner.gif", type1: "Rock", type2: "", location: "Asado Desert <span class='emoji-highlight'>🏛️</span><span class='scarlet-highlight'>🔴only</span>", evolve: "" },
	{ id: "320", name: "Eiscue", img: "eiscue.gif", type1: "Ice", type2: "", location: "North Paldean Sea <span class='emoji-highlight'>🌊🏖️</span><span class='violet-highlight'>🟣only</span>", evolve: "" },
	{ id: "321", name: "Pincurchin", img: "pincurchin.gif", type1: "Electric", type2: "", location: "East 1 & 2 <span class='emoji-highlight'>🏖️</span> <span class='percent'>10%</span>", evolve: "" },
	{ id: "322", name: "Sandygast", img: "sandygast.gif", type1: "Ghost", type2: "Ground", location: "East 1 & 2 <span class='emoji-highlight'>🏖️</span>", evolve: "" },
	{ id: "323", name: "Palossand", img: "palossand.gif", type1: "Ghost", type2: "Ground", location: "West 2 <span class='emoji-highlight'>🏖️</span> <span class='percent'>20%</span>", evolve: "Sandygast (Lvl 42)" },
	{ id: "324", name: "Slowpoke", img: "slowpoke.gif", type1: "Water", type2: "Psychic", location: "Casseroya Lake <span class='emoji-highlight'>⛵🎣🏖️</span>", evolve: "" },
	{ id: "325", name: "Slowbro", img: "slowbro.gif", type1: "Water", type2: "Psychic", location: "Casseroya Lake <span class='emoji-highlight'>⛵🎣🏖️</span>", evolve: "Slowpoke (Lvl 37)" },
	{ id: "326", name: "Slowking", img: "slowking.gif", type1: "Water", type2: "Psychic", location: "None", evolve: "Slowpoke (Trade Holding King's Rock)" },
	{ id: "327", name: "Shellos", img: "shellos.gif", type1: "Water", type2: "", location: "West 2 <span class='emoji-highlight'>🏖️</span>", evolve: "" },
	{ id: "328", name: "Gastrodon", img: "gastrodon.gif", type1: "Water", type2: "Ground", location: "North 2 <span class='emoji-highlight'>🏖️</span> <span class='percent'>20%</span>", evolve: "" },
	{ id: "329", name: "Shellder", img: "shellder.gif", type1: "Water", type2: "", location: "East 1 & 2 <span class='emoji-highlight'>🌊🏖️</span>", evolve: "" },
	{ id: "330", name: "Cloyster", img: "cloyster.gif", type1: "Water", type2: "Ice", location: "North 1 & 3 <span class='emoji-highlight'>🌊</span> <span class='percent'>10%</span>", evolve: "Shellder (Water Stone)" },
	{ id: "331", name: "Qwilfish", img: "qwilfish.gif", type1: "Water", type2: "Poison", location: "East Paldean Sea <span class='emoji-highlight'>🌊</span>", evolve: "" },
	{ id: "332", name: "Luvdisc", img: "luvdisc.gif", type1: "Water", type2: "", location: "East Paldean Sea <span class='emoji-highlight'>🌊</span>", evolve: "" },
	{ id: "333", name: "Finneon", img: "finneon.gif", type1: "Water", type2: "", location: "West Paldean Sea <span class='emoji-highlight'>🌊</span>", evolve: "" },
	{ id: "334", name: "Lumineon", img: "lumineon.gif", type1: "Water", type2: "", location: "West Paldean Sea <span class='emoji-highlight'>🌊</span>", evolve: "Finneon (Lvl 31)" },
	{ id: "335", name: "Bruxish", img: "bruxish.gif", type1: "Water", type2: "Psychic", location: "East Paldean Sea <span class='emoji-highlight'>🌊</span>", evolve: "" },
	{ id: "336", name: "Alomomola", img: "alomomola.gif", type1: "Water", type2: "", location: "North Paldean Sea <span class='emoji-highlight'>🌊</span> <span class='percent'>10%</span>", evolve: "" },
	{ id: "337", name: "Skrelp", img: "skrelp.gif", type1: "Poison", type2: "Water", location: "North Paldean Sea <span class='emoji-highlight'>🌊</span><span class='scarlet-highlight'>🔴only</span>", evolve: "" },
	{ id: "338", name: "Dragalge", img: "dragalge.gif", type1: "Poison", type2: "Dragon", location: "North Paldean Sea <span class='emoji-highlight'>🌊</span> <span class='percent'>20%</span><span class='scarlet-highlight'>🔴only</span>", evolve: "Skrelp (Lvl 48)" },
	{ id: "339", name: "Clauncher", img: "clauncher.gif", type1: "Water", type2: "", location: "West Paldean Sea <span class='emoji-highlight'>🌊</span><span class='violet-highlight'>🟣only</span>", evolve: "" },
	{ id: "340", name: "Clawitzer", img: "clawitzer.gif", type1: "Water", type2: "", location: "North Paldean Sea <span class='emoji-highlight'>🌊</span> <span class='percent'>20%</span><span class='violet-highlight'>🟣only</span>", evolve: "Clauncher (Lvl 37)" },
	{ id: "341", name: "Tynamo", img: "tynamo.gif", type1: "Electric", type2: "", location: "North Paldean Sea <span class='emoji-highlight'>🌊</span>", evolve: "" },
	{ id: "342", name: "Eelektrik", img: "eelektrik.gif", type1: "Electric", type2: "", location: "North Paldean Sea <span class='emoji-highlight'>🎣🌊</span>", evolve: "Tynamo (Lvl 39)" },
	{ id: "343", name: "Eelektross", img: "eelektross.gif", type1: "Electric", type2: "", location: "None", evolve: "Elektrik (Thunder Stone)" },
	{ id: "344", name: "Mareanie", img: "mareanie.gif", type1: "Poison", type2: "Water", location: "East Paldean Sea <span class='emoji-highlight'>🌊🏖️</span>", evolve: "" },
	{ id: "345", name: "Toxapex", img: "toxapex.gif", type1: "Poison", type2: "Water", location: "East Paldean Sea <span class='emoji-highlight'>🌊🏖️</span> <span class='percent'>3%</span>", evolve: "Mareanie (Lvl 38)" },
	{ id: "346", name: "Flamigo", img: "flamigo.gif", type1: "Flying", type2: "Fighting", location: "Casseroya Lake <span class='emoji-highlight'>⛵</span> <span class='percent'>10%</span>", evolve: "" },
	{ id: "347", name: "Dratini", img: "dratini.gif", type1: "Dragon", type2: "", location: "Casseroya Lake <span class='emoji-highlight'>⛵</span>", evolve: "" },
	{ id: "348", name: "Dragonair", img: "dragonair.gif", type1: "Dragon", type2: "", location: "Casseroya Lake <span class='emoji-highlight'>⛵</span> <span class='percent'>10%</span>", evolve: "Dratini (Lvl 30)" },
	{ id: "349", name: "Dragonite", img: "dragonite.gif", type1: "Dragon", type2: "Flying", location: "None", evolve: "Dragonair (Lvl 55)" },
	{ id: "350", name: "Snom", img: "snom.gif", type1: "Ice", type2: "Bug", location: "Glaseado Mountain <span class='emoji-highlight'>⛰️❄️</span>", evolve: "" },
	{ id: "351", name: "Frosmoth", img: "frosmoth.gif", type1: "Ice", type2: "Bug", location: "Great Crater <span class='emoji-highlight'>🌱</span> <span class='percent'>5%</span>", evolve: "Snom (High Friendship at Night)" },
	{ id: "352", name: "Snover", img: "snover.gif", type1: "Grass", type2: "Ice", location: "Glaseado Mountain <span class='emoji-highlight'>🏡❄️</span>", evolve: "" },
	{ id: "353", name: "Abomasnow", img: "abomasnow.gif", type1: "Grass", type2: "Ice", location: "Glaseado Mountain <span class='emoji-highlight'>❄️</span> <span class='percent'>20%</span>", evolve: "Snover (Lvl 40)" },
	{ id: "354", name: "Delibird", img: "delibird.gif", type1: "Ice", type2: "Flying", location: "Glaseado Mountain <span class='emoji-highlight'>🏡❄️</span> <span class='percent'>10%</span>", evolve: "" },
	{ id: "355", name: "Cubchoo", img: "cubchoo.gif", type1: "Ice", type2: "", location: "Glaseado Mountain <span class='emoji-highlight'>❄️</span>", evolve: "" },
	{ id: "356", name: "Beartic", img: "beartic.gif", type1: "Ice", type2: "", location: "Glaseado Mountain <span class='emoji-highlight'>❄️</span> <span class='percent'>20%</span>", evolve: "Cubchoo (Lvl 37)" },
	{ id: "357", name: "Snorunt", img: "snorunt.gif", type1: "Ice", type2: "", location: "Glaseado Mountain <span class='emoji-highlight'>❄️🦇</span>", evolve: "" },
	{ id: "358", name: "Glalie", img: "glalie.gif", type1: "Ice", type2: "", location: "Glaseado Mountain <span class='emoji-highlight'>❄️</span> <span class='percent'>20%</span>", evolve: "Snorunt (Lvl 42)" },
	{ id: "359", name: "Froslass", img: "froslass.gif", type1: "Ice", type2: "Ghost", location: "Glaseado Mountain <span class='emoji-highlight'>❄️</span> <span class='percent'>2%</span>", evolve: "Snorunt (Dawn Stone on Female)" },
	{ id: "360", name: "Cryogonal", img: "cryogonal.gif", type1: "Ice", type2: "", location: "Glaseado Mountain <span class='emoji-highlight'>❄️</span> <span class='percent'>1%</span>", evolve: "" },
	{ id: "361", name: "Cetoddle", img: "cetoddle.gif", type1: "Ice", type2: "", location: "Glaseado Mountain <span class='emoji-highlight'>⛰️❄️</span>", evolve: "" },
	{ id: "362", name: "Cetitan", img: "cetitan.gif", type1: "Ice", type2: "", location: "Glaseado Mountain <span class='emoji-highlight'>❄️</span> <span class='percent'>10%</span>", evolve: "Cetoddle (Ice Stone)" },
	{ id: "363", name: "Bergmite", img: "bergmite.gif", type1: "Ice", type2: "", location: "Glaseado Mountain <span class='emoji-highlight'>❄️🌊</span>", evolve: "" },
	{ id: "364", name: "Avalugg", img: "avalugg.gif", type1: "Ice", type2: "", location: "Casseroya Lake <span class='emoji-highlight'>⛵</span>", evolve: "Bergmite (Lvl 37)" },
	{ id: "365", name: "Rufflet", img: "rufflet.gif", type1: "Normal", type2: "Flying", location: "Asado Desert <span class='emoji-highlight'>🏜️</span>", evolve: "" },
	{ id: "366", name: "Braviary", img: "braviary.gif", type1: "Normal", type2: "Flying", location: "North 1 & 2 <span class='emoji-highlight'>⛰️🪨</span> <span class='percent'>20%</span>", evolve: "Rufflet (Lvl 54)" },
	{ id: "367", name: "Pawniard", img: "pawniard.gif", type1: "Dark", type2: "Steel", location: "East 3 <span class='emoji-highlight'>🎣🪨</span>", evolve: "" },
	{ id: "368", name: "Bisharp", img: "bisharp.gif", type1: "Dark", type2: "Steel", location: "North 2 <span class='emoji-highlight'>🎣🪨🎋</span> <span class='percent'>10%</span>", evolve: "Pawniard (Lvl 52)" },
	{ id: "369", name: "Kingambit", img: "kingambit.gif", type1: "Dark", type2: "Steel", location: "None", evolve: "Bisharp (Look Up Instructions)" },
	{ id: "370", name: "Deino", img: "deino.gif", type1: "Dark", type2: "Dragon", location: "Glaseado Mountain <span class='emoji-highlight'>🦇</span><span class='scarlet-highlight'>🔴only</span>", evolve: "" },
	{ id: "371", name: "Zweilous", img: "zweilous.gif", type1: "Dark", type2: "Dragon", location: "Great Crater <span class='emoji-highlight'>🕳️</span> <span class='percent'>20%</span><span class='scarlet-highlight'>🔴only</span>", evolve: "Deino (Lvl 50)" },
	{ id: "372", name: "Hydreigon", img: "hydreigon.gif", type1: "Dark", type2: "Dragon", location: "None", evolve: "Zweilous (Lvl 64)" },
	{ id: "373", name: "Veluza", img: "veluza.gif", type1: "Water", type2: "Psychic", location: "Casseroya Lake <span class='emoji-highlight'>⛵🌊</span>", evolve: "" },
	{ id: "374", name: "Dondozo", img: "dondozo.gif", type1: "Water", type2: "", location: "Casseroya Lake <span class='emoji-highlight'>⛵</span>", evolve: "" },
	{ id: "375", name: "Tatsugiri", img: "tatsugiri.gif", type1: "Dragon", type2: "Water", location: "Casseroya Lake <span class='emoji-highlight'>⛵</span> <span class='percent'>20%</span>", evolve: "" },
	{ id: "376", name: "Great Tusk", img: "greattusk.gif", type1: "Ground", type2: "Fighting", location: "Great Crater <span class='emoji-highlight'>🕳️</span> <span class='percent'>10%</span><span class='scarlet-highlight'>🔴only</span>", evolve: "" },
	{ id: "377", name: "Scream Tail", img: "screamtail.gif", type1: "Fairy", type2: "Psychic", location: "Great Crater <span class='emoji-highlight'>🌱🕳️</span> <span class='percent'>20%</span><span class='scarlet-highlight'>🔴only</span>", evolve: "" },
	{ id: "378", name: "Brute Bonnet", img: "brutebonnet.gif", type1: "Grass", type2: "Dark", location: "Great Crater <span class='emoji-highlight'>🌱🕳️</span> <span class='percent'>10%</span><span class='scarlet-highlight'>🔴only</span>", evolve: "" },
	{ id: "379", name: "Flutter Mane", img: "fluttermane.gif", type1: "Ghost", type2: "Fairy", location: "Great Crater <span class='emoji-highlight'>🦇</span> <span class='percent'>15%</span><span class='scarlet-highlight'>🔴only</span>", evolve: "" },
	{ id: "380", name: "Slither Wing", img: "slitherwing.gif", type1: "Bug", type2: "Fighting", location: "Great Crater <span class='emoji-highlight'>🌱</span> <span class='percent'>15%</span><span class='scarlet-highlight'>🔴only</span>", evolve: "" },
	{ id: "381", name: "Sandy Shocks", img: "sandyshocks.gif", type1: "Electric", type2: "Ground", location: "Great Crater <span class='emoji-highlight'>🪨</span> <span class='percent'>15%</span><span class='scarlet-highlight'>🔴only</span>", evolve: "" },
	{ id: "382", name: "Iron Treads", img: "irontreads.gif", type1: "Ground", type2: "Steel", location: "Great Crater <span class='emoji-highlight'>🕳️</span> <span class='percent'>10%</span><span class='violet-highlight'>🟣only</span>", evolve: "" },
	{ id: "383", name: "Iron Bundle", img: "ironbundle.gif", type1: "Ice", type2: "Water", location: "Great Crater <span class='emoji-highlight'>🌱🕳️</span> <span class='percent'>20%</span><span class='violet-highlight'>🟣only</span>", evolve: "" },
	{ id: "384", name: "Iron Hands", img: "ironhands.gif", type1: "Fighting", type2: "Electric", location: "Great Crater <span class='emoji-highlight'>🌱🕳️</span> <span class='percent'>10%</span><span class='violet-highlight'>🟣only</span>", evolve: "" },
	{ id: "385", name: "Iron Jugulis", img: "ironjugulis.gif", type1: "Dark", type2: "Flying", location: "Great Crater <span class='emoji-highlight'>🦇</span> <span class='percent'>15%</span><span class='violet-highlight'>🟣only</span>", evolve: "" },
	{ id: "386", name: "Iron Moth", img: "ironmoth.gif", type1: "Fire", type2: "Poison", location: "Great Crater <span class='emoji-highlight'>🌱</span> <span class='percent'>15%</span><span class='violet-highlight'>🟣only</span>", evolve: "" },
	{ id: "387", name: "Iron Thorns", img: "ironthorns.gif", type1: "Rock", type2: "Electric", location: "Great Crater <span class='emoji-highlight'>🪨</span> <span class='percent'>15%</span><span class='violet-highlight'>🟣only</span>", evolve: "" },
	{ id: "388", name: "Frigibax", img: "frigibax.gif", type1: "Dragon", type2: "Ice", location: "Glaseado Mountain <span class='emoji-highlight'>❄️🦇</span> <span class='percent'>1%</span>", evolve: "" },
	{ id: "389", name: "Arctibax", img: "arctibax.gif", type1: "Dragon", type2: "Ice", location: "North 3 <span class='emoji-highlight'>🦇</span>", evolve: "Frigibax (Lvl 35)" },
	{ id: "390", name: "Baxcalibur", img: "baxcalibur.gif", type1: "Dragon", type2: "Ice", location: "None", evolve: "Arctibax (Lvl 54)" },
	{ id: "391", name: "Gimmighoul", img: "gimmighoul.gif", type1: "Ghost", type2: "", location: "17 Locations", evolve: "" },
	{ id: "392", name: "Gholdengo", img: "gholdengo.gif", type1: "Steel", type2: "Ghost", location: "None", evolve: "Gimmighoul (Collect 999 Coins)" },
	{ id: "393", name: "Wo-Chien", img: "wochien.gif", type1: "Dark", type2: "Grass", location: "Purple Shrine", evolve: "" },
	{ id: "394", name: "Chien-Pao", img: "chienpao.gif", type1: "Dark", type2: "Ice", location: "Yellow Shrine", evolve: "" },
	{ id: "395", name: "Ting-Lu", img: "tinglu.gif", type1: "Dark", type2: "Ground", location: "Green Shrine", evolve: "" },
	{ id: "396", name: "Chi-Yu", img: "chiyu.gif", type1: "Dark", type2: "Fire", location: "Blue Shrine", evolve: "" },
	{ id: "397", name: "Roaring Moon", img: "roaringmoon.gif", type1: "Dragon", type2: "Dark", location: "Great Crater <span class='emoji-highlight'>🦇</span><span class='scarlet-highlight'>🔴only</span>", evolve: "" },
	{ id: "398", name: "Iron Valiant", img: "ironvaliant.gif", type1: "Fairy", type2: "Fighting", location: "Great Crater <span class='emoji-highlight'>🦇</span><span class='violet-highlight'>🟣only</span>", evolve: "" },
	{ id: "399", name: "Koraidon", img: "koraidon.gif", type1: "Fighting", type2: "Dragon", location: "Starter <span class='scarlet-highlight'>🔴only</span>", evolve: "" },
	{ id: "400", name: "Miraidon", img: "miraidon.gif", type1: "Electric", type2: "Dragon", location: "Starter <span class='violet-highlight'>🟣only</span>", evolve: "" }
];