const pokedexData = [
  { id: "001", name: "Grookey", img: "grookey.gif", type1: "Grass", type2: "", location: "Starter", evolve: "" },
  { id: "002", name: "Thwackey", img: "thwackey.gif", type1: "Grass", type2: "", location: "Evolve or Trade", evolve: "Grookey (Lvl 16)" },
  { id: "003", name: "Rillaboom", img: "rillaboom.gif", type1: "Grass", type2: "", location: "Evolve or Trade", evolve: "Thwackey (Lvl 35)" },
  { id: "004", name: "Scorbunny", img: "scorbunny.gif", type1: "Fire", type2: "", location: "Starter", evolve: "" },
  { id: "005", name: "Raboot", img: "raboot.gif", type1: "Fire", type2: "", location: "Evolve or Trade", evolve: "Scorbunny (Lvl 16)" },
  { id: "006", name: "Cinderace", img: "cinderace.gif", type1: "Fire", type2: "", location: "Evolve or Trade", evolve: "Raboot (Lvl 35)" },
  { id: "007", name: "Sobble", img: "sobble.gif", type1: "Water", type2: "", location: "Starter", evolve: "" },
  { id: "008", name: "Drizzile", img: "drizzile.gif", type1: "Water", type2: "", location: "Evolve or Trade", evolve: "Sobble (Lvl 16)" },
  { id: "009", name: "Inteleon", img: "inteleon.gif", type1: "Water", type2: "", location: "Evolve or Trade", evolve: "Drizzile (Lvl 35)" },
  { id: "010", name: "Blipbug", img: "blipbug.gif", type1: "Bug", type2: "", location: "Route 2<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "011", name: "Dottler", img: "dottler.gif", type1: "Bug", type2: "Psychic", location: "Giant's Cap<span class='encounter-highlight'>👁️🔍</span>", evolve: "Blipbug (Lvl 10)" },
  { id: "012", name: "Orbeetle", img: "orbeetle.gif", type1: "Bug", type2: "Psychic", location: "Slumbering Weald<span class='encounter-highlight'>👁️🔍</span>", evolve: "Dottler (Lvl 30)" },
  { id: "013", name: "Caterpie", img: "caterpie.gif", type1: "Bug", type2: "", location: "Route 1<span class='encounter-highlight'>🔍</span>", evolve: "" },
  { id: "014", name: "Metapod", img: "metapod.gif", type1: "Bug", type2: "", location: "Rolling Fields<span class='encounter-highlight'>👁️</span>", evolve: "Caterpie (Lvl 7)" },
  { id: "015", name: "Butterfree", img: "butterfree.gif", type1: "Bug", type2: "Flying", location: "East Lake Axewell<span class='encounter-highlight'>👁️</span>", evolve: "Metapod (Lvl 10)" },
  { id: "016", name: "Grubbin", img: "grubbin.gif", type1: "Bug", type2: "", location: "Route 1<span class='encounter-highlight'>🔍</span>", evolve: "" },
  { id: "017", name: "Charjabug", img: "charjabug.gif", type1: "Bug", type2: "Electric", location: "Axew's Eye<span class='emoji-highlight'>☔</span><span class='encounter-highlight'>🔍</span>", evolve: "Grubbin (Lvl 20)" },
  { id: "018", name: "Vikavolt", img: "vikavolt.gif", type1: "Bug", type2: "Electric", location: "Giant's Seat<span class='emoji-highlight'>🪟☀️⛅🌪️</span><span class='encounter-highlight'>📍</span>", evolve: "Charjabug (Thunder Stone)" },
  { id: "019", name: "Hoothoot", img: "hoothoot.gif", type1: "Normal", type2: "Flying", location: "Dappled Grove<span class='emoji-highlight'>🪟⛅</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "020", name: "Noctowl", img: "noctowl.gif", type1: "Normal", type2: "Flying", location: "Motostoke Outskirts<span class='encounter-highlight'>👁️</span>", evolve: "Hoothoot (Lvl 20)" },
  { id: "021", name: "Rookidee", img: "rookidee.gif", type1: "Flying", type2: "", location: "Route 1<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "022", name: "Corvisquire", img: "corvisquire.gif", type1: "Flying", type2: "", location: "Giant's Mirror<span class='encounter-highlight'>👁️</span>", evolve: "Rookidee (Lvl 18)" },
  { id: "023", name: "Corviknight", img: "corviknight.gif", type1: "Flying", type2: "Steel", location: "Lake of Outrage<span class='encounter-highlight'>🔍</span>", evolve: "Corvisquire (Lvl 38)" },
  { id: "024", name: "Skwovet", img: "skwovet.gif", type1: "Normal", type2: "", location: "Route 1<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "025", name: "Greedent", img: "greedent.gif", type1: "Normal", type2: "", location: "Route 6<span class='encounter-highlight'>🌳</span>", evolve: "Skwovet (Lvl 24)" },
  { id: "026", name: "Pidove", img: "pidove.gif", type1: "Normal", type2: "Water", location: "Rolling Fields<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "027", name: "Tranquill", img: "tranquill.gif", type1: "Normal", type2: "Flying", location: "Stony Wilderness<span class='encounter-highlight'>👁️</span>", evolve: "Pidove (Lvl 21)" },
  { id: "028", name: "Unfezant", img: "unfezant.gif", type1: "Normal", type2: "Flying", location: "Hammerlocke Hills<span class='encounter-highlight'>👁️</span>", evolve: "Tranquill (Lvl 32)" },
  { id: "029", name: "Nickit", img: "nickit.gif", type1: "Dark", type2: "", location: "Dusty Bowl<span class='emoji-highlight'>🪟☀️⛅☔</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "030", name: "Thievul", img: "thievul.gif", type1: "Dark", type2: "", location: "Route 7<span class='encounter-highlight'>👁️</span>", evolve: "Nickit (Lvl 18)" },
  { id: "031g", name: "Galarian Zigzagoon", img: "zigzagoon-galar.gif", type1: "Dark", type2: "Normal", location: "Route 3<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "032g", name: "Galarian Linoone", img: "linoone-galar.gif", type1: "Dark", type2: "Normal", location: "Giant's Cap<span class='emoji-highlight'>🪟⛅</span><span class='encounter-highlight'>👁️</span>", evolve: "Galarian Zigzagoon (Lvl 20)" },
  { id: "033", name: "Obstagoon", img: "obstagoon.gif", type1: "Dark", type2: "Normal", location: "Bridge Field<span class='encounter-highlight'>📍</span>", evolve: "Galarian Linoone (Lvl 35 at Night)" },
  { id: "034", name: "Wooloo", img: "wooloo.gif", type1: "Normal", type2: "", location: "Route 1<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "035", name: "Dubwool", img: "dubwool.gif", type1: "Normal", type2: "", location: "Dusty Bowl<span class='emoji-highlight'>🪟</span><span class='encounter-highlight'>🔍</span>", evolve: "Wooloo (Lvl 24)" },
  { id: "036", name: "Lotad", img: "lotad.gif", type1: "Water", type2: "Grass", location: "West Lake Axewell<span class='emoji-highlight'>⛅⚡</span><span class='encounter-highlight'>👁️</span><span class='shield-highlight'>🛡️only</span>", evolve: "" },
  { id: "037", name: "Lombre", img: "lombre.gif", type1: "Water", type2: "Grass", location: "Dappled Grove<span class='encounter-highlight'>👁️</span><span class='shield-highlight'>🛡️only</span>", evolve: "Lotad (Lvl 14)" },
  { id: "038", name: "Ludicolo", img: "ludicolo.gif", type1: "Water", type2: "Grass", location: "Dappled Grove<span class='encounter-highlight'>📍</span><span class='shield-highlight'>🛡️only</span>", evolve: "Lombre (Water Stone)" },
  { id: "039", name: "Seedot", img: "seedot.gif", type1: "Grass", type2: "", location: "West Lake Axewell<span class='emoji-highlight'>⛅⚡</span><span class='encounter-highlight'>👁️</span><span class='shield-highlight'>🛡️only</span>", evolve: "" },
  { id: "040", name: "Nuzleaf", img: "nuzleaf.gif", type1: "Grass", type2: "Dark", location: "Dappled Grove<span class='encounter-highlight'>👁️</span> <span class='percent'>5%</span><span class='sword-highlight'>🗡️only</span>", evolve: "Seedot (Lvl 14)" },
  { id: "041", name: "Shiftry", img: "shiftry.gif", type1: "Grass", type2: "Dark", location: "Dappled Grove<span class='encounter-highlight'>📍</span><span class='sword-highlight'>🗡️only</span>", evolve: "Nuzleaf (Leaf Stone)" },
  { id: "042", name: "Chewtle", img: "chewtle.gif", type1: "Water", type2: "", location: "Giant's Cap<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "043", name: "Drednaw", img: "drednaw.gif", type1: "Water", type2: "Rock", location: "Giant's Cap<span class='emoji-highlight'>☔⚡</span><span class='encounter-highlight'>👁️</span>", evolve: "Chewtle (Lvl 22)" },
  { id: "044", name: "Purrloin", img: "purrloin.gif", type1: "Dark", type2: "", location: "Motostoke Riverbank<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "045", name: "Liepard", img: "liepard.gif", type1: "Dark", type2: "", location: "Route 7<span class='encounter-highlight'>👁️🔍</span>", evolve: "Purrloin (Lvl 20)" },
  { id: "046", name: "Yamper", img: "yamper.gif", type1: "Electric", type2: "", location: "Route 4<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "047", name: "Boltund", img: "boltund.gif", type1: "Electric", type2: "", location: "North Lake Miloch<span class='encounter-highlight'>📍</span>", evolve: "Yamper (Lvl 25)" },
  { id: "048", name: "Bunnelby", img: "bunnelby.gif", type1: "Normal", type2: "", location: "Rolling Fields<span class='encounter-highlight'>👁️🔍</span>", evolve: "" },
  { id: "049", name: "Diggersby", img: "diggersby.gif", type1: "Normal", type2: "", location: "Giant's Cap<span class='emoji-highlight'>☀️🌪️</span><span class='encounter-highlight'>👁️</span>", evolve: "Bunnelby (Lvl 20)" },
  { id: "050", name: "Minccino", img: "minccino.gif", type1: "Normal", type2: "", location: "Route 5<span class='encounter-highlight'>👁️</span> <span class='percent'>15%</span>", evolve: "" },
  { id: "051", name: "Cinccino", img: "cinccino.gif", type1: "Normal", type2: "", location: "Giant's Cap<span class='emoji-highlight'>🪟⛅🌫️</span><span class='encounter-highlight'>📍</span>", evolve: "Minccino (Shiny Stone)" },
  { id: "052", name: "Bounsweet", img: "bounsweet.gif", type1: "Grass", type2: "", location: "Stony Wilderness<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "053", name: "Steenee", img: "steenee.gif", type1: "Grass", type2: "", location: "Axew's Eye<span class='emoji-highlight'>🪟</span><span class='encounter-highlight'>🔍</span> <span class='percent'>10%</span>", evolve: "Bounsweet (Lvl 18)" },
  { id: "054", name: "Tsareena", img: "tsareena.gif", type1: "Grass", type2: "", location: "Stony Wilderness<span class='encounter-highlight'>📍</span>", evolve: "Steenee (Lvl Up w/ Stomp)" },
  { id: "055", name: "Oddish", img: "oddish.gif", type1: "Grass", type2: "Poison", location: "Dappled Grove<span class='emoji-highlight'>🪟⛅☔⚡</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "056", name: "Gloom", img: "gloom.gif", type1: "Grass", type2: "Poison", location: "Giant's Cap<span class='emoji-highlight'>⚡</span><span class='encounter-highlight'>👁️</span>", evolve: "Oddish (Lvl 21)" },
  { id: "057", name: "Vileplume", img: "vileplume.gif", type1: "Grass", type2: "Poison", location: "Hammerlocke Hills<span class='emoji-highlight'>🪟☀️☔⚡</span><span class='encounter-highlight'>📍</span>", evolve: "Gloom (Leaf Stone)" },
  { id: "058", name: "Bellossom", img: "bellossom.gif", type1: "Grass", type2: "", location: "Giant's Mirror<span class='emoji-highlight'>🪟☀️🌫️</span><span class='encounter-highlight'>📍</span>", evolve: "Gloom (Sun Stone)" },
  { id: "059", name: "Budew", img: "budew.gif", type1: "Grass", type2: "Poison", location: "East Lake Axewell<span class='emoji-highlight'>⛅</span><span class='encounter-highlight'>🔍</span>", evolve: "Breed Roselia Holding Rose Incense" },
  { id: "060", name: "Roselia", img: "roselia.gif", type1: "Grass", type2: "Poison", location: "Axew's Eye<span class='emoji-highlight'>⛅</span><span class='encounter-highlight'>🔍</span>", evolve: "Budew (Max Friendship)" },
  { id: "061", name: "Roserade", img: "roserade.gif", type1: "Grass", type2: "Poison", location: "Hammerlocke Hills<span class='emoji-highlight'>⛅🌫️</span><span class='encounter-highlight'>📍</span>", evolve: "Roselia (Shiny Stone)" },
  { id: "062", name: "Wingull", img: "wingull.gif", type1: "Water", type2: "Flying", location: "East Lake Axewell<span class='encounter-highlight'>🌊</span>", evolve: "" },
  { id: "063", name: "Pelipper", img: "pelipper.gif", type1: "Water", type2: "Flying", location: "Route 9<span class='encounter-highlight'>👁️🌊</span>", evolve: "Wingull (Lvl 25)" },
  { id: "064", name: "Joltik", img: "joltik.gif", type1: "Bug", type2: "Electric", location: "Giant's Mirror<span class='emoji-highlight'>⚡</span><span class='encounter-highlight'>👁️🔍</span>", evolve: "" },
  { id: "065", name: "Galvantula", img: "galvantula.gif", type1: "Bug", type2: "Electric", location: "Route 7<span class='encounter-highlight'>👁️</span>", evolve: "Joltik (Lvl 36)" },
  { id: "066", name: "Electrike", img: "electrike.gif", type1: "Electric", type2: "", location: "Route 4<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "067", name: "Manectric", img: "manectric.gif", type1: "Electric", type2: "", location: "Giant's Seat<span class='emoji-highlight'>⚡</span><span class='encounter-highlight'>🔍</span>", evolve: "Electrike (Lvl 26)" },
  { id: "068", name: "Vulpix", img: "vulpix.gif", type1: "Fire", type2: "", location: "Dusty Bowl<span class='emoji-highlight'>☀️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "069", name: "Ninetales", img: "ninetales.gif", type1: "Fire", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>☀️</span><span class='encounter-highlight'>👁️</span><span class='sword-highlight'>🗡️only</span>", evolve: "Vulpix (Fire Stone)" },
  { id: "070", name: "Growlithe", img: "growlithe.gif", type1: "Fire", type2: "", location: "Dusty Bowl<span class='emoji-highlight'>☀️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "071", name: "Arcanine", img: "arcanine.gif", type1: "Fire", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>☀️</span><span class='shield-highlight'>🛡️only</span>", evolve: "Growlithe (Fire Stone)" },
  { id: "072", name: "Vanillite", img: "vanillite.gif", type1: "Ice", type2: "", location: "West Lake Axewell<span class='emoji-highlight'>❄️🌨️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "073", name: "Vanillish", img: "vanillish.gif", type1: "Ice", type2: "", location: "Dappled Grove<span class='emoji-highlight'>❄️🌨️</span><span class='encounter-highlight'>📍</span>", evolve: "Vanillite (Lvl 35)" },
  { id: "074", name: "Vanilluxe", img: "vanilluxe.gif", type1: "Ice", type2: "", location: "Bridge Field<span class='emoji-highlight'>❄️🌨️</span><span class='encounter-highlight'>📍</span>", evolve: "Vanillish (Lvl 47)" },
  { id: "075", name: "Swinub", img: "swinub.gif", type1: "Ice", type2: "Ground", location: "Rolling Fields<span class='emoji-highlight'>❄️🌨️</span><span class='encounter-highlight'>🔍</span>", evolve: "" },
  { id: "076", name: "Piloswine", img: "piloswine.gif", type1: "Ice", type2: "Ground", location: "Dusty Bowl<span class='emoji-highlight'>❄️🌨️</span><span class='encounter-highlight'>📍</span>", evolve: "Swinub (Lvl 33)" },
  { id: "077", name: "Mamoswine", img: "mamoswine.gif", type1: "Ice", type2: "Ground", location: "Evolve or Trade", evolve: "Piloswine (Lvl Up w/ Ancient Power)" },
  { id: "078", name: "Delibird", img: "delibird.gif", type1: "Ice", type2: "Flying", location: "Dappled Grove<span class='emoji-highlight'>❄️🌨️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "079", name: "Snorunt", img: "snorunt.gif", type1: "Ice", type2: "", location: "West Lake Axewell<span class='emoji-highlight'>❄️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "080", name: "Glalie", img: "glalie.gif", type1: "Ice", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>❄️</span><span class='encounter-highlight'>👁️</span>", evolve: "Snorunt (Lvl 42)" },
  { id: "081", name: "Froslass", img: "froslass.gif", type1: "Ice", type2: "Ghost", location: "Evolve or Trade", evolve: "Snorunt (Dawn Stone)" },
  { id: "082", name: "Baltoy", img: "baltoy.gif", type1: "Ground", type2: "Psychic", location: "East Lake Axewell<span class='emoji-highlight'>🌪️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "083", name: "Claydol", img: "claydol.gif", type1: "Ground", type2: "Psychic", location: "Bridge Field<span class='emoji-highlight'>☀️🌪️</span><span class='encounter-highlight'>📍</span>", evolve: "Baltoy (Lvl 36)" },
  { id: "084", name: "Mudbray", img: "mudbray.gif", type1: "Ground", type2: "", location: "Giant's Seat<span class='emoji-highlight'>☀️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "085", name: "Mudsdale", img: "mudsdale.gif", type1: "Ground", type2: "", location: "Axew's Eye<span class='emoji-highlight'>🌪️</span><span class='encounter-highlight'>👁️</span>", evolve: "Mudbray (Lvl 30)" },
  { id: "086", name: "Dwebble", img: "dwebble.gif", type1: "Bug", type2: "Rock", location: "West Lake Axewell<span class='emoji-highlight'>☀️🌪️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "087", name: "Crustle", img: "crustle.gif", type1: "Bug", type2: "Rock", location: "Stony Wilderness<span class='encounter-highlight'>📍</span>", evolve: "Dwebble (Lvl 34)" },
  { id: "088", name: "Golett", img: "golett.gif", type1: "Ground", type2: "Ghost", location: "Giant's Seat<span class='emoji-highlight'>🌪️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "089", name: "Golurk", img: "golurk.gif", type1: "Ground", type2: "Ghost", location: "Lake of Outrage<span class='encounter-highlight'>👁️</span>", evolve: "Golett (Lvl 43)" },
  { id: "090", name: "Munna", img: "munna.gif", type1: "Psychic", type2: "", location: "East Lake Axewell<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "091", name: "Musharna", img: "musharna.gif", type1: "Psychic", type2: "", location: "Giant's Seat<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>📍</span>", evolve: "Munna (Moon Stone)" },
  { id: "092", name: "Natu", img: "natu.gif", type1: "Psychic", type2: "Flying", location: "Giant's Seat<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>📍</span>", evolve: "" },
  { id: "093", name: "Xatu", img: "xatu.gif", type1: "Psychic", type2: "Flying", location: "East Lake Axewell<span class='encounter-highlight'>📍</span>", evolve: "Natu (Lvl 25)" },
  { id: "094", name: "Stufful", img: "stufful.gif", type1: "Normal", type2: "Fighting", location: "East Lake Axewel<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "095", name: "Bewear", img: "bewear.gif", type1: "Normal", type2: "Fighting", location: "Axew's Eye<span class='encounter-highlight'>👁️</span>", evolve: "Stufful (Lvl 27)" },
  { id: "096", name: "Snover", img: "snover.gif", type1: "Grass", type2: "Ice", location: "Route 10<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "097", name: "Abomasnow", img: "abomasnow.gif", type1: "Grass", type2: "Ice", location: "Lake of Outrage<span class='emoji-highlight'>❄️</span><span class='encounter-highlight'>👁️</span>", evolve: "Snover (Lvl 40)" },
  { id: "098", name: "Krabby", img: "krabby.gif", type1: "Water", type2: "", location: "South Lake Miloch<span class='emoji-highlight'>⛅☔⚡❄️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "099", name: "Kingler", img: "kingler.gif", type1: "Water", type2: "", location: "West Lake Axewell<span class='encounter-highlight'>📍</span>", evolve: "Krabby (Lvl 28)" },
  { id: "100", name: "Wooper", img: "wooper.gif", type1: "Water", type2: "Ground", location: "West Lake Axewell<span class='emoji-highlight'>🪟☔⚡</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "101", name: "Quagsire", img: "quagsire.gif", type1: "Water", type2: "Ground", location: "West Lake Axewell<span class='emoji-highlight'>🪟☔⚡</span><span class='encounter-highlight'>📍</span>", evolve: "Wooper (Lvl 20)" },
  { id: "102", name: "Corphish", img: "corphish.gif", type1: "Water", type2: "", location: "South Lake Miloch<span class='emoji-highlight'>🪟⚡</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "103", name: "Crawdaunt", img: "crawdaunt.gif", type1: "Water", type2: "Dark", location: "South Lake Miloch<span class='emoji-highlight'>🪟⚡</span><span class='encounter-highlight'>📍</span>", evolve: "Corphish (Lvl 30)" },
  { id: "104", name: "Nincada", img: "nincada.gif", type1: "Bug", type2: "Ground", location: "South Lake Miloch<span class='emoji-highlight'>🌪️</span><span class='encounter-highlight'>🔍</span>", evolve: "" },
  { id: "105", name: "Ninjask", img: "ninjask.gif", type1: "Bug", type2: "Flying", location: "Stony Wilderness<span class='emoji-highlight'>🪟☔</span><span class='encounter-highlight'>👁️</span>", evolve: "Nincada (Lvl 20)" },
  { id: "106", name: "Shedinja", img: "shedinja.gif", type1: "Bug", type2: "Ghost", location: "Evolve or Trade", evolve: "Nincada (Lvl 20 w/ Open Party Slot)" },
  { id: "107", name: "Tyrogue", img: "tyrogue.gif", type1: "Fighting", type2: "", location: "Rolling Fields<span class='emoji-highlight'>⛅</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "108", name: "Hitmonlee", img: "hitmonlee.gif", type1: "Fighting", type2: "", location: "Dusty Bowl<span class='emoji-highlight'>⛅</span><span class='encounter-highlight'>👁️</span> <span class='percent'>5%</span><span class='sword-highlight'>🗡️only</span>", evolve: "Tyrogue (Lvl 20 w/ Attack > Defense)" },
  { id: "109", name: "Hitmonchan", img: "hitmonchan.gif", type1: "Fighting", type2: "", location: "Dusty Bowl<span class='emoji-highlight'>⛅</span><span class='encounter-highlight'>👁️</span> <span class='percent'>5%</span><span class='shield-highlight'>🛡️only</span>", evolve: "Hitmonlee (Lvl 20 w/ Attack < Defense)" },
  { id: "110", name: "Hitmontop", img: "hitmontop.gif", type1: "Fighting", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>⛅</span><span class='encounter-highlight'>👁️</span> <span class='percent'>2%</span>", evolve: "Hitmonchan (Lvl 20 w/ Attack = Defense)" },
  { id: "111", name: "Pancham", img: "pancham.gif", type1: "Fighting", type2: "", location: "Rolling Fields<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "112", name: "Pangoro", img: "pangoro.gif", type1: "Fighting", type2: "Dark", location: "Rolling Fields<span class='emoji-highlight'>🪟⛅☔☀️</span><span class='encounter-highlight'>📍</span>", evolve: "Pancham (Lvl 32 w/ Dark Type in Party)" },
  { id: "113", name: "Klink", img: "klink.gif", type1: "Steel", type2: "", location: "North Lake Miloch<span class='emoji-highlight'>❄️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "114", name: "Klang", img: "klang.gif", type1: "Steel", type2: "", location: "Hammerlocke Hills<span class='emoji-highlight'>🪟⛅☔❄️</span><span class='encounter-highlight'>📍</span>", evolve: "Klink (Lvl 38)" },
  { id: "115", name: "Klinklang", img: "klinklang.gif", type1: "Steel", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>🌨️</span><span class='encounter-highlight'>👁️</span>", evolve: "Klang (Lvl 49)" },
  { id: "116", name: "Combee", img: "combee.gif", type1: "Bug", type2: "Flying", location: "Rolling Fields<span class='emoji-highlight'>🪟</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "117", name: "Vespiquen", img: "vespiquen.gif", type1: "Bug", type2: "Flying", location: "Rolling Fields<span class='emoji-highlight'>🪟</span><span class='encounter-highlight'>📍</span>", evolve: "Combee (Lvl 21 Female)" },
  { id: "118", name: "Bronzor", img: "bronzor.gif", type1: "Steel", type2: "Psychic", location: "Giant's Seat<span class='emoji-highlight'>🪟☔⚡🌪️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "119", name: "Bronzong", img: "bronzong.gif", type1: "Steel", type2: "Psychic", location: "Dusty Bowl<span class='encounter-highlight'>📍</span>", evolve: "Bronzor (Lvl 33)" },
  { id: "120", name: "Ralts", img: "ralts.gif", type1: "Psychic", type2: "Fairy", location: "Rolling Fields<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "121", name: "Kirlia", img: "kirlia.gif", type1: "Psychic", type2: "Fairy", location: "Rolling Fields<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>📍</span>", evolve: "Ralts (Lvl 20)" },
  { id: "122", name: "Gardevoir", img: "gardevoir.gif", type1: "Psychic", type2: "Fairy", location: "Rolling Fields<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>📍</span>", evolve: "Kirlia (Lvl 30)" },
  { id: "123", name: "Gallade", img: "gallade.gif", type1: "Psychic", type2: "Fighting", location: "Bridge Field<span class='encounter-highlight'>📍</span>", evolve: "Kirlia (Dawn Stone on Male)" },
  { id: "124", name: "Drifloon", img: "drifloon.gif", type1: "Ghost", type2: "Flying", location: "South Lake Miloch<span class='encounter-highlight'>🌊</span>", evolve: "" },
  { id: "125", name: "Drifblim", img: "drifblim.gif", type1: "Ghost", type2: "Flying", location: "Axew's Eye<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>👁️</span>", evolve: "Drifloon (Lvl 28)" },
  { id: "126", name: "Gossifleur", img: "gossifleur.gif", type1: "Grass", type2: "", location: "Route 3<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "127", name: "Eldegoss", img: "eldegoss.gif", type1: "Grass", type2: "", location: "Motostoke Riverbank<span class='encounter-highlight'>📍</span>", evolve: "Gossifleur (Lvl 20)" },
  { id: "128", name: "Cherubi", img: "cherubi.gif", type1: "Grass", type2: "", location: "North Lake Miloch<span class='encounter-highlight'>🌳</span>", evolve: "" },
  { id: "129", name: "Cherrim", img: "cherrim.gif", type1: "Grass", type2: "", location: "Evolve or Trade", evolve: "Cherubi (Lvl 25)" },
  { id: "130", name: "Stunky", img: "stunky.gif", type1: "Poison", type2: "Dark", location: "North Lake Miloch<span class='emoji-highlight'>🪟☀️🌪️🌫️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "131", name: "Skuntank", img: "skuntank.gif", type1: "Poison", type2: "Dark", location: "North Lake Miloch<span class='emoji-highlight'>☔☀️🌪️</span><span class='encounter-highlight'>📍</span>", evolve: "Stunky (Lvl 34)" },
  { id: "132", name: "Tympole", img: "tympole.gif", type1: "Water", type2: "Ground", location: "Dappled Grove<span class='emoji-highlight'>☔⚡</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "133", name: "Palpitoad", img: "palpitoad.gif", type1: "Water", type2: "Ground", location: "North Lake Miloch<span class='emoji-highlight'>☔⚡</span><span class='encounter-highlight'>👁️</span>", evolve: "Tympole (Lvl 25)" },
  { id: "134", name: "Seismitoad", img: "seismitoad.gif", type1: "Water", type2: "Ground", location: "Bridge Field<span class='emoji-highlight'>⛅☔⚡🌫️</span><span class='encounter-highlight'>📍</span>", evolve: "Palpitoad (Lvl 36)" },
  { id: "135", name: "Duskull", img: "duskull.gif", type1: "Ghost", type2: "", location: "Watchtower Ruins<span class='emoji-highlight'>⛅☔⚡️🌫️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "136", name: "Dusclops", img: "dusclops.gif", type1: "Ghost", type2: "", location: "Watchtower Ruins<span class='emoji-highlight'>⛅☔⚡🌫️</span><span class='encounter-highlight'>📍</span>", evolve: "Duskull (Lvl 37)" },
  { id: "137", name: "Dusknoir", img: "dusknoir.gif", type1: "Ghost", type2: "", location: "Stony Wilderness<span class='encounter-highlight'>📍</span>", evolve: "Dusclops (Trade holding Reaper Cloth)" },
  { id: "138", name: "Machop", img: "machop.gif", type1: "Fighting", type2: "", location: "South Lake Miloch<span class='emoji-highlight'>⛅☀️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "139", name: "Machoke", img: "machoke.gif", type1: "Fighting", type2: "", location: "Hammerlocke Hills<span class='emoji-highlight'>⛅☔🌪️</span><span class='encounter-highlight'>👁️</span>", evolve: "Machop (Lvl 28)" },
  { id: "140", name: "Machamp", img: "machamp.gif", type1: "Fighting", type2: "", location: "Giant's Mirror<span class='encounter-highlight'>📍</span>", evolve: "Machoke (Trade)" },
  { id: "141", name: "Gastly", img: "gastly.gif", type1: "Ghost", type2: "Poison", location: "Watchtower Ruins<span class='emoji-highlight'>⚡🌪️🌫️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "142", name: "Haunter", img: "haunter.gif", type1: "Ghost", type2: "Poison", location: "Watchtower Ruins<span class='encounter-highlight'>📍</span>", evolve: "Gastly (Lvl 25)" },
  { id: "143", name: "Gengar", img: "gengar.gif", type1: "Ghost", type2: "Poison", location: "Giants Cap<span class='encounter-highlight'>📍</span>", evolve: "Haunter (Trade)" },
  { id: "144", name: "Magikarp", img: "magikarp.gif", type1: "Water", type2: "", location: "Route 2<span class='encounter-highlight'>🎣</span>", evolve: "" },
  { id: "145", name: "Gyarados", img: "gyarados.gif", type1: "Water", type2: "Flying", location: "Bridge Field<span class='encounter-highlight'>🌊</span>", evolve: "Magikarp (Lvl 20)" },
  { id: "146", name: "Goldeen", img: "goldeen.gif", type1: "Water", type2: "", location: "Bridge Field<span class='emoji-highlight'>🪟⛅☔🌪️</span><span class='encounter-highlight'>🎣</span>", evolve: "" },
  { id: "147", name: "Seaking", img: "seaking.gif", type1: "Water", type2: "", location: "Bridge Field<span class='emoji-highlight'>☀️⛅🌪️</span><span class='encounter-highlight'>🌊</span>", evolve: "Goldeen (Lvl 33)" },
  { id: "148", name: "Remoraid", img: "remoraid.gif", type1: "Water", type2: "", location: "South Lake Miloch<span class='encounter-highlight'>🎣</span>", evolve: "" },
  { id: "149", name: "Octillery", img: "octillery.gif", type1: "Water", type2: "", location: "Route 9<span class='encounter-highlight'>🎣</span>", evolve: "Remoraid (Lvl 25)" },
  { id: "150", name: "Shellder", img: "shellder.gif", type1: "Water", type2: "", location: "Giant's Seat<span class='encounter-highlight'>🎣</span>", evolve: "" },
  { id: "151", name: "Cloyster", img: "cloyster.gif", type1: "Water", type2: "Ice", location: "Giant's Seat<span class='encounter-highlight'>🎣</span> <span class='percent'>5%</span>", evolve: "Shellder (Water Stone)" },
  { id: "152", name: "Feebas", img: "feebas.gif", type1: "Water", type2: "", location: "Route 2<span class='encounter-highlight'>🎣</span> <span class='percent'>1%</span>", evolve: "" },
  { id: "153", name: "Milotic", img: "milotic.gif", type1: "Water", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>🌊</span>", evolve: "Feebas (Trade holding Prism Scale)" },
  { id: "154", name: "Basculin", img: "basculin.gif", type1: "Water", type2: "", location: "Motostoke Riverbank<span class='encounter-highlight'>🌊</span>", evolve: "" },
  { id: "155", name: "Wishiwashi", img: "wishiwashi.gif", type1: "Water", type2: "", location: "Route 9<span class='encounter-highlight'>🎣</span>", evolve: "" },
  { id: "156", name: "Pyukumuku", img: "pyukumuku.gif", type1: "Water", type2: "", location: "Giant's Seat<span class='encounter-highlight'>🎣</span>", evolve: "" },
  { id: "157", name: "Trubbish", img: "trubbish.gif", type1: "Poison", type2: "", location: "Route 3<span class='encounter-highlight'>👁️</span> <span class='percent'>5%</span>", evolve: "" },
  { id: "158", name: "Garbodor", img: "garbodor.gif", type1: "Poison", type2: "", location: "Motostoke Riverbank<span class='encounter-highlight'>📍</span>", evolve: "Trubbish (Lvl 36)" },
  { id: "159", name: "Sizzlipede", img: "sizzlipede.gif", type1: "Fire", type2: "Bug", location: "Route 3<span class='encounter-highlight'>🔍</span> <span class='percent'>1%</span>", evolve: "" },
  { id: "160", name: "Centiskorch", img: "centiskorch.gif", type1: "Fire", type2: "Bug", location: "Evolve or Trade", evolve: "Sizzlipede (Lvl 28)" },
  { id: "161", name: "Rolycoly", img: "rolycoly.gif", type1: "Rock", type2: "", location: "Giant's Cap<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "162", name: "Carkol", img: "carkol.gif", type1: "Rock", type2: "Fire", location: "Giant's Cap<span class='emoji-highlight'>☀️🌪️</span><span class='encounter-highlight'>👁️</span>", evolve: "Rolycoly (Lvl 18)" },
  { id: "163", name: "Coalossal", img: "coalossal.gif", type1: "Rock", type2: "Fire", location: "Giant's Cap<span class='encounter-highlight'>📍</span>", evolve: "Carkol (Lvl 34)" },
  { id: "164", name: "Diglett", img: "diglett.gif", type1: "Ground", type2: "", location: "Rolling Fields<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "165", name: "Dugtrio", img: "dugtrio.gif", type1: "Ground", type2: "", location: "Giant's Mirror<span class='encounter-highlight'>👁️</span>", evolve: "Diglett (Lvl 26)" },
  { id: "166", name: "Drilbur", img: "drilbur.gif", type1: "Ground", type2: "", location: "Giant's Mirror<span class='emoji-highlight'>🌪️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "167", name: "Excadrill", img: "excadrill.gif", type1: "Ground", type2: "Steel", location: "Giant's Mirror<span class='encounter-highlight'>👁️</span>", evolve: "Drilbur (Lvl 31)" },
  { id: "168", name: "Roggenrola", img: "roggenrola.gif", type1: "Rock", type2: "", location: "Rolling Fields<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "169", name: "Boldore", img: "boldore.gif", type1: "Rock", type2: "", location: "Rolling Fields<span class='encounter-highlight'>👁️</span> <span class='percent'>10%</span>", evolve: "Roggenrola (Lvl 25)" },
  { id: "170", name: "Gigalith", img: "gigalith.gif", type1: "Rock", type2: "", location: "Dusty Bowl<span class='emoji-highlight'>🪟☀️</span><span class='encounter-highlight'>📍</span>", evolve: "Boldore (Trade)" },
  { id: "171", name: "Timburr", img: "timburr.gif", type1: "Fighting", type2: "", location: "Galar Mine<span class='encounter-highlight'>👁️</span><span class='sword-highlight'>🗡️25%</span><span class='shield-highlight'>🛡️5%</span>", evolve: "" },
  { id: "172", name: "Gurdurr", img: "gurdurr.gif", type1: "Fighting", type2: "", location: "Route 8<span class='encounter-highlight'>👁️</span>", evolve: "Timburr (Lvl 25)" },
  { id: "173", name: "Conkeldurr", img: "conkeldurr.gif", type1: "Fighting", type2: "", location: "Motostoke Riverbank<span class='encounter-highlight'>📍</span>", evolve: "Gurdurr (Trade)" },
  { id: "174", name: "Woobat", img: "woobat.gif", type1: "Psychic", type2: "Flying", location: "Watchtower Ruins<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "175", name: "Swoobat", img: "swoobat.gif", type1: "Psychic", type2: "Flying", location: "Evolve or Trade", evolve: "Woobat (Max Friendship)" },
  { id: "176", name: "Noibat", img: "noibat.gif", type1: "Flying", type2: "Dragon", location: "Watchtower Ruins<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "177", name: "Noivern", img: "noivern.gif", type1: "Flying", type2: "Dragon", location: "Bridge Field<span class='encounter-highlight'>📍</span>", evolve: "Noibat (Lvl 48)" },
  { id: "178", name: "Onix", img: "onix.gif", type1: "Rock", type2: "Ground", location: "Rolling Fields<span class='encounter-highlight'>📍</span>", evolve: "" },
  { id: "179", name: "Steelix", img: "steelix.gif", type1: "Steel", type2: "Ground", location: "Giant's Seat<span class='encounter-highlight'>📍</span>", evolve: "Onix (Trade holding Metal Coat)" },
  { id: "180", name: "Arrokuda", img: "arrokuda.gif", type1: "Water", type2: "", location: "Motostoke Riverbank<span class='encounter-highlight'>🌊</span>", evolve: "" },
  { id: "181", name: "Barraskewda", img: "barraskewda.gif", type1: "Water", type2: "", location: "Dusty Bowl<span class='encounter-highlight'>🎣</span>", evolve: "Arrokuda (Lvl 26)" },
  { id: "182", name: "Meowth", img: "meowth.gif", type1: "Normal", type2: "", location: "Trade for Galarian Meowth in Grass Gym", evolve: "" },
  { id: "182g", name: "Galarian Meowth", img: "meowth-galar.gif", type1: "Steel", type2: "", location: "Route 4<span class='encounter-highlight'>👁️🔍</span>", evolve: "" },
  { id: "183", name: "Perrserker", img: "perrserker.gif", type1: "Steel", type2: "", location: "Route 7<span class='encounter-highlight'>👁️</span>", evolve: "Galarian Meowth (Lvl 28)" },
  { id: "184", name: "Persian", img: "persian.gif", type1: "Normal", type2: "", location: "Evolve or Trade", evolve: "Meowth (Lvl 28)" },
  { id: "185", name: "Milcery", img: "milcery.gif", type1: "Fairy", type2: "", location: "Route 4<span class='encounter-highlight'>🔍</span>", evolve: "" },
  { id: "186", name: "Alcremie", img: "alcremie.gif", type1: "Fairy", type2: "", location: "Evolve or Trade", evolve: "Milcery (Spin around holding sweet item)" },
  { id: "187", name: "Cutiefly", img: "cutiefly.gif", type1: "Bug", type2: "Fairy", location: "Bridge Field<span class='emoji-highlight'>🪟⛅☀️🌫️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "188", name: "Ribombee", img: "ribombee.gif", type1: "Bug", type2: "Fairy", location: "Bridge Field<span class='emoji-highlight'>🪟⛅☀️🌫️</span><span class='encounter-highlight'>📍</span>", evolve: "Cutiefly (Lvl 25)" },
  { id: "189", name: "Ferroseed", img: "ferroseed.gif", type1: "Grass", type2: "Steel", location: "Motostoke Riverbank<span class='emoji-highlight'>🌨️</span><span class='encounter-highlight'>🔍</span> <span class='percent'>10%</span>", evolve: "" },
  { id: "190", name: "Ferrothorn", img: "ferrothorn.gif", type1: "Grass", type2: "Steel", location: "Dusty Bowl<span class='emoji-highlight'>🌨️</span><span class='encounter-highlight'>🔍</span> <span class='percent'>10%</span>", evolve: "Ferroseed (Lvl 40)" },
  { id: "191", name: "Pumpkaboo", img: "pumpkaboo.gif", type1: "Ghost", type2: "Grass", location: "Hammerlocke Hills<span class='emoji-highlight'>⚡</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "192", name: "Gourgeist", img: "gourgeist.gif", type1: "Ghost", type2: "Grass", location: "Hammerlocke Hills<span class='encounter-highlight'>📍</span>", evolve: "Pumpkaboo (Trade)" },
  { id: "193", name: "Pichu", img: "pichu.gif", type1: "Electric", type2: "", location: "Breed or Trade", evolve: "Breed Pikachu" },
  { id: "194", name: "Pikachu", img: "pikachu.gif", type1: "Electric", type2: "", location: "Rolling Fields<span class='emoji-highlight'>⚡</span><span class='encounter-highlight'>📍</span>", evolve: "Pichu (High Friendship)" },
  { id: "195", name: "Raichu", img: "raichu.gif", type1: "Electric", type2: "", location: "Evolve or Trade", evolve: "Pikachu (Thunder Stone)" },
  { id: "196", name: "Eevee", img: "eevee.gif", type1: "Normal", type2: "", location: "Route 4<span class='encounter-highlight'>👁️</span><span class='sword-highlight'>🗡️1%</span><span class='shield-highlight'>🛡️5%</span>", evolve: "Breed any Eeveelution" },
  { id: "197", name: "Vaporeon", img: "vaporeon.gif", type1: "Water", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>☔</span><span class='encounter-highlight'>📍</span>", evolve: "Eevee (Water Stone)" },
  { id: "198", name: "Jolteon", img: "jolteon.gif", type1: "Electric", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>⚡</span><span class='encounter-highlight'>📍</span>", evolve: "Eevee (Thunder Stone)" },
  { id: "199", name: "Flareon", img: "flareon.gif", type1: "Fire", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>☀️</span><span class='encounter-highlight'>📍</span>", evolve: "Eevee (Fire Stone)" },
  { id: "200", name: "Espeon", img: "espeon.gif", type1: "Psychic", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>⛅</span><span class='encounter-highlight'>📍</span>", evolve: "Eevee (High friendship during day)" },
  { id: "201", name: "Umbreon", img: "umbreon.gif", type1: "Dark", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>🌪️</span><span class='encounter-highlight'>📍</span>", evolve: "Eevee (High friendship at night)" },
  { id: "202", name: "Leafeon", img: "leafeon.gif", type1: "Grass", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>🪟</span><span class='encounter-highlight'>📍</span>", evolve: "Eevee (Leaf Stone)" },
  { id: "203", name: "Glaceon", img: "glaceon.gif", type1: "Ice", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>❄️🌨️</span><span class='encounter-highlight'>📍</span>", evolve: "Eevee (Ice Stone)" },
  { id: "204", name: "Sylveon", img: "sylveon.gif", type1: "Fairy", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>📍</span>", evolve: "Eevee (Max Affection w/ Fairy move)" },
  { id: "205", name: "Applin", img: "applin.gif", type1: "Grass", type2: "Dragon", location: "Giant's Mirror<span class='emoji-highlight'>⚡</span><span class='encounter-highlight'>🔍</span>", evolve: "" },
  { id: "206", name: "Flapple", img: "flapple.gif", type1: "Grass", type2: "Dragon", location: "Evolve<span class='sword-highlight'>🗡️only</span> or Trade", evolve: "Applin (Tart Apple)" },
  { id: "207", name: "Appletun", img: "appletun.gif", type1: "Grass", type2: "Dragon", location: "Evolve<span class='shield-highlight'>🛡️only</span> or Trade", evolve: "Flapple (Sweet Apple)" },
  { id: "208", name: "Espurr", img: "espurr.gif", type1: "Psychic", type2: "", location: "Route 5<span class='encounter-highlight'>🔍</span>", evolve: "" },
  { id: "209", name: "Meowstic", img: "meowstic.gif", type1: "Psychic", type2: "", location: "Dusty Bowl<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>🔍</span>", evolve: "Espurr (Lvl 25)" },
  { id: "210", name: "Swirlix", img: "swirlix.gif", type1: "Fairy", type2: "", location: "Route 5<span class='encounter-highlight'>👁️</span><span class='sword-highlight'>🗡️only</span>", evolve: "" },
  { id: "211", name: "Slurpuff", img: "slurpuff.gif", type1: "Fairy", type2: "", location: "Trade Only", evolve: "Swirlix (Trade holding Whipped Dream)" },
  { id: "212", name: "Spritzee", img: "spritzee.gif", type1: "Fairy", type2: "", location: "Route 5<span class='encounter-highlight'>👁️</span><span class='sword-highlight'>🛡️only</span>", evolve: "" },
  { id: "213", name: "Aromatisse", img: "aromatisse.gif", type1: "Fairy", type2: "", location: "Trade Only", evolve: "Spritzee (Trade holding Sachet)" },
  { id: "214", name: "Dewpider", img: "dewpider.gif", type1: "Water", type2: "Bug", location: "Stony Wilderness<span class='emoji-highlight'>☔⚡</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "215", name: "Araquanid", img: "araquanid.gif", type1: "Water", type2: "Bug", location: "Stony Wilderness<span class='emoji-highlight'>☔⚡</span><span class='encounter-highlight'>📍</span>", evolve: "Dewpider (Lvl 22)" },
  { id: "216", name: "Wynaut", img: "wynaut.gif", type1: "Psychic", type2: "", location: "Breed or Trade", evolve: "Breed Wobbuffet holding Lax Incense" },
  { id: "217", name: "Wobbuffet", img: "wobbuffet.gif", type1: "Psychic", type2: "", location: "Route 5<span class='emoji-highlight'>🪟⛅☔⚡</span><span class='encounter-highlight'>👁️</span>", evolve: "Wynaut (Lvl 15)" },
  { id: "218g", name: "Galarian Farfetch'd", img: "farfetchd-galar.gif", type1: "Fighting", type2: "", location: "Route 5<span class='encounter-highlight'>👁️</span> <span class='percent'>5%</span><span class='sword-highlight'>🗡️only</span>", evolve: "" },
  { id: "219", name: "Sirfetch'd", img: "sirfetchd.gif", type1: "Fighting", type2: "", location: "Evolve or Trade", evolve: "Galarian Farfetch'd (Get 3 Crit Hits in One Battle)" },
  { id: "220", name: "Chinchou", img: "chinchou.gif", type1: "Water", type2: "Electric", location: "East Lake Axewell<span class='encounter-highlight'>🌊</span>", evolve: "" },
  { id: "221", name: "Lanturn", img: "lanturn.gif", type1: "Water", type2: "Electric", location: "Lake of Outrage<span class='encounter-highlight'>🎣</span>", evolve: "Chinchou (Lvl 27)" },
  { id: "222", name: "Croagunk", img: "croagunk.gif", type1: "Poison", type2: "Fighting", location: "Dusty Bowl<span class='emoji-highlight'>⛅</span><span class='shield-highlight'>🛡️only</span>", evolve: "" },
  { id: "223", name: "Toxicroak", img: "toxicroak.gif", type1: "Poison", type2: "Fighting", location: "Evolve or Trade", evolve: "Croagunk (Lvl 37)" },
  { id: "224", name: "Scraggy", img: "scraggy.gif", type1: "Dark", type2: "Fighting", location: "Dusty Bowl<span class='emoji-highlight'>⛅</span><span class='sword-highlight'>🗡️only</span>", evolve: "" },
  { id: "225", name: "Scrafty", img: "scrafty.gif", type1: "Dark", type2: "Fighting", location: "Evolve or Trade", evolve: "Scraggy (Lvl 39)" },
  { id: "226g", name: "Galarian Stunfisk", img: "stunfisk-galar.gif", type1: "Ground", type2: "Steel", location: "Dusty Bowl<span class='emoji-highlight'>☀️</span><span class='encounter-highlight'>🔍</span>", evolve: "" },
  { id: "227", name: "Shuckle", img: "shuckle.gif", type1: "Bug", type2: "Rock", location: "Watchtower Ruins<span class='emoji-highlight'>🌪️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "228", name: "Barboach", img: "barboach.gif", type1: "Water", type2: "Ground", location: "Galar Mine No. 2<span class='encounter-highlight'>🎣</span>", evolve: "" },
  { id: "229", name: "Whiscash", img: "whiscash.gif", type1: "Water", type2: "Ground", location: "Slumbering Weald<span class='encounter-highlight'>🎣</span>", evolve: "Barboach (Lvl 30)" },
  { id: "230", name: "Shellos", img: "shellos.gif", type1: "Water", type2: "", location: "Dusty Bowl<span class='encounter-highlight'>🌊</span>", evolve: "" },
  { id: "231", name: "Gastrodon", img: "gastrodon.gif", type1: "Water", type2: "Ground", location: "Route 9<span class='encounter-highlight'>👁️</span>", evolve: "Shellos (Lvl 30)" },
  { id: "232", name: "Wimpod", img: "wimpod.gif", type1: "Bug", type2: "Water", location: "Giant's Mirror<span class='emoji-highlight'>☔</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "233", name: "Golisopod", img: "golisopod.gif", type1: "Bug", type2: "Water", location: "Bridge Field<span class='emoji-highlight'>🪟☔⚡</span><span class='encounter-highlight'>📍</span>", evolve: "Wimpod (Lvl 30)" },
  { id: "234", name: "Binacle", img: "binacle.gif", type1: "Rock", type2: "Water", location: "Galar Mine No. 2<span class='encounter-highlight'>👁️</span><span class='percent'>15%</span>", evolve: "" },
  { id: "235", name: "Barbaracle", img: "barbaracle.gif", type1: "Rock", type2: "Water", location: "Dusty Bowl<span class='emoji-highlight'>⛅☔⚡</span><span class='encounter-highlight'>📍</span>", evolve: "Binacle (Lvl 39)" },
  { id: "236g", name: "Galarian Corsola", img: "corsola-galar.gif", type1: "Ghost", type2: "", location: "Giant's Mirror<span class='emoji-highlight'>⛅</span><span class='encounter-highlight'>👁️</span> <span class='percent'>5%</span><span class='shield-highlight'>🛡️only</span>", evolve: "" },
  { id: "237", name: "Cursola", img: "cursola.gif", type1: "Ghost", type2: "", location: "Evolve or Trade", evolve: "Galarian Corsola (Lvl 38)" },
  { id: "238", name: "Impidimp", img: "impidimp.gif", type1: "Dark", type2: "Fairy", location: "Stony Wilderness<span class='encounter-highlight'>🔍</span>", evolve: "" },
  { id: "239", name: "Morgrem", img: "morgrem.gif", type1: "Dark", type2: "Fairy", location: "Glimwood Tangle<span class='encounter-highlight'>🔍</span>", evolve: "Impidimp (Lvl 32)" },
  { id: "240", name: "Grimmsnarl", img: "grimmsnarl.gif", type1: "Dark", type2: "Fairy", location: "Stony Wilderness<span class='encounter-highlight'>📍</span>", evolve: "Morgrem (Lvl 42)" },
  { id: "241", name: "Hatenna", img: "hatenna.gif", type1: "Psychic", type2: "", location: "Stony Wilderness<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "242", name: "Hattrem", img: "hattrem.gif", type1: "Psychic", type2: "", location: "Glimwood Tangle<span class='encounter-highlight'>🔍</span>", evolve: "Hatenna (Lvl 32)" },
  { id: "243", name: "Hatterene", img: "hatterene.gif", type1: "Psychic", type2: "Fairy", location: "Lake of Outrage<span class='encounter-highlight'>👁️</span>", evolve: "Hattrem (Lvl 42)" },
  { id: "244", name: "Salandit", img: "salandit.gif", type1: "Poison", type2: "Fire", location: "Motostoke Riverbank<span class='emoji-highlight'>☀️</span><span class='encounter-highlight'>👁️</span><span class='shield-highlight'>🛡️only</span>", evolve: "" },
  { id: "245", name: "Salazzle", img: "salazzle.gif", type1: "Poison", type2: "Fire", location: "Evolve or Trade", evolve: "Salandit (Lvl 33 Female)" },
  { id: "246", name: "Pawniard", img: "pawniard.gif", type1: "Dark", type2: "Steel", location: "Giant's Mirror<span class='emoji-highlight'>🌨️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "247", name: "Bisharp", img: "bisharp.gif", type1: "Dark", type2: "Steel", location: "Giant's Seat<span class='encounter-highlight'>📍</span>", evolve: "Pawniard (Lvl 52)" },
  { id: "248", name: "Throh", img: "throh.gif", type1: "Fighting", type2: "", location: "Giant's Mirror<span class='emoji-highlight'>⛅</span><span class='encounter-highlight'>👁️</span> <span class='percent'>10%</span><span class='shield-highlight'>🛡️only</span>", evolve: "" },
  { id: "249", name: "Sawk", img: "sawk.gif", type1: "Fighting", type2: "", location: "Giant's Mirror<span class='emoji-highlight'>⛅</span><span class='encounter-highlight'>👁️</span> <span class='percent'>10%</span><span class='sword-highlight'>🗡️only</span>", evolve: "" },
  { id: "250", name: "Koffing", img: "koffing.gif", type1: "Poison", type2: "", location: "Motostoke Outskirts<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "251g", name: "Galarian Weezing", img: "weezing-galar.gif", type1: "Poison", type2: "Fairy", location: "Slumbering Weald<span class='encounter-highlight'>👁️🔍</span>", evolve: "Koffing (Lvl 35)" },
  { id: "252", name: "Bonsly", img: "bonsly.gif", type1: "Rock", type2: "", location: "Stony Wilderness<span class='emoji-highlight'>🌪️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "253", name: "Sudowoodo", img: "sudowoodo.gif", type1: "Rock", type2: "", location: "Motostoke Outskirts<span class='encounter-highlight'>👁️</span>", evolve: "Bonsly (Lvl Up w/ Mimic)" },
  { id: "254", name: "Cleffa", img: "cleffa.gif", type1: "Fairy", type2: "", location: "Breed or Trade", evolve: "Breed Clefairy" },
  { id: "255", name: "Clefairy", img: "clefairy.gif", type1: "Fairy", type2: "", location: "Motostoke Outskirts<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>👁️</span>", evolve: "Cleffa (High Friendship)" },
  { id: "256", name: "Clefable", img: "clefable.gif", type1: "Fairy", type2: "", location: "Motostoke Riverbank<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>📍</span>", evolve: "Clefairy (Moon Stone)" },
  { id: "257", name: "Togepi", img: "togepi.gif", type1: "Fairy", type2: "", location: "Bridge Field<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>🔍</span> <span class='percent'>5%</span>", evolve: "" },
  { id: "258", name: "Togetic", img: "togetic.gif", type1: "Fairy", type2: "Flying", location: "Stony Wilderness<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>🔍</span> <span class='percent'>10%</span>", evolve: "Togepi (Friendship)" },
  { id: "259", name: "Togekiss", img: "togekiss.gif", type1: "Fairy", type2: "Flying", location: "Dusty Bowl<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>👁️</span> <span class='percent'>2%</span>", evolve: "Togetic (Shiny Stone)" },
  { id: "260", name: "Munchlax", img: "munchlax.gif", type1: "Normal", type2: "", location: "Motostoke Riverbank<span class='emoji-highlight'>🪟</span><span class='encounter-highlight'>👁️</span> <span class='percent'>5%</span>", evolve: "Breed Snorlax holding Full Incense" },
  { id: "261", name: "Snorlax", img: "snorlax.gif", type1: "Normal", type2: "", location: "Motostoke Riverbank<span class='encounter-highlight'>📍</span>", evolve: "Munchlax (High Friendship)" },
  { id: "262", name: "Cottonee", img: "cottonee.gif", type1: "Grass", type2: "Fairy", location: "Stony Wilderness<span class='emoji-highlight'>⛅</span><span class='encounter-highlight'>🔍</span>", evolve: "" },
  { id: "263", name: "Whimsicott", img: "whimsicott.gif", type1: "Grass", type2: "Fairy", location: "Evolve or Trade", evolve: "Cottonee (Sun Stone)" },
  { id: "264", name: "Rhyhorn", img: "rhyhorn.gif", type1: "Ground", type2: "Rock", location: "Giant's Cap<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "265", name: "Rhydon", img: "rhydon.gif", type1: "Ground", type2: "Rock", location: "Dusty Bowl<span class='encounter-highlight'>📍</span>", evolve: "Rhyhorn (Lvl 42)" },
  { id: "266", name: "Rhyperior", img: "rhyperior.gif", type1: "Ground", type2: "Rock", location: "Trade Only", evolve: "Rhydon (Trade holding Protector)" },
  { id: "267", name: "Gothita", img: "gothita.gif", type1: "Psychic", type2: "", location: "Giant's Cap<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>👁️</span><span class='sword-highlight'>🗡️only</span>", evolve: "" },
  { id: "268", name: "Gothorita", img: "gothorita.gif", type1: "Psychic", type2: "", location: "Giant's Cap<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>👁️</span><span class='sword-highlight'>🗡️only</span>", evolve: "Gothita (Lvl 32)" },
  { id: "269", name: "Gothitelle", img: "gothitelle.gif", type1: "Psychic", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>👁️</span> <span class='percent'>13%</span><span class='sword-highlight'>🗡️only</span>", evolve: "Gothorita (Lvl 41)" },
  { id: "270", name: "Solosis", img: "solosis.gif", type1: "Psychic", type2: "", location: "Giant's Cap<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>👁️</span><span class='shield-highlight'>🛡️only</span>", evolve: "" },
  { id: "271", name: "Duosion", img: "duosion.gif", type1: "Psychic", type2: "", location: "Dusty Bowl<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>👁️</span> <span class='percent'>10%</span><span class='shield-highlight'>🛡️only</span>", evolve: "Solosis (Lvl 32)" },
  { id: "272", name: "Reuniclus", img: "reuniclus.gif", type1: "Psychic", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>👁️</span> <span class='percent'>13%</span><span class='shield-highlight'>🛡️only</span>", evolve: "Duosion (Lvl 41)" },
  { id: "273", name: "Karrablast", img: "karrablast.gif", type1: "Bug", type2: "", location: "Route 7<span class='encounter-highlight'>🔍</span>", evolve: "" },
  { id: "274", name: "Escavalier", img: "escavalier.gif", type1: "Bug", type2: "Steel", location: "Trade Only", evolve: "Karrablast (Trade for a Shelmet)" },
  { id: "275", name: "Shelmet", img: "shelmet.gif", type1: "Bug", type2: "", location: "Motostoke Riverbank<span class='emoji-highlight'>☔</span><span class='encounter-highlight'>🔍</span> <span class='percent'>10%</span>", evolve: "" },
  { id: "276", name: "Accelgor", img: "accelgor.gif", type1: "Bug", type2: "", location: "Trade Only", evolve: "Shelmet (Trade for a Karrablast)" },
  { id: "277", name: "Elgyem", img: "elgyem.gif", type1: "Psychic", type2: "", location: "Motostoke Riverbank<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "278", name: "Beheeyem", img: "beheeyem.gif", type1: "Psychic", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>🪟</span><span class='encounter-highlight'>👁️</span>", evolve: "Elgyem (Lvl 42)" },
  { id: "279", name: "Cubchoo", img: "cubchoo.gif", type1: "Ice", type2: "", location: "Route 10<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "280", name: "Beartic", img: "beartic.gif", type1: "Ice", type2: "", location: "Route 10<span class='encounter-highlight'>🔍</span>", evolve: "Cubchoo (Lvl 37)" },
  { id: "281", name: "Rufflet", img: "rufflet.gif", type1: "Normal", type2: "Flying", location: "Route 8<span class='encounter-highlight'>👁️</span><span class='sword-highlight'>🗡️only</span>", evolve: "" },
  { id: "282", name: "Braviary", img: "braviary.gif", type1: "Normal", type2: "Flying", location: "Dusty Bowl<span class='encounter-highlight'>👁️</span><span class='sword-highlight'>🗡️only</span>", evolve: "Rufflet (Lvl 54)" },
  { id: "283", name: "Vullaby", img: "vullaby.gif", type1: "Dark", type2: "Flying", location: "Route 8<span class='encounter-highlight'>👁️</span><span class='shield-highlight'>🛡️only</span>", evolve: "" },
  { id: "284", name: "Mandibuzz", img: "mandibuzz.gif", type1: "Dark", type2: "Flying", location: "Dusty Bowl<span class='encounter-highlight'>👁️</span><span class='shield-highlight'>🛡️only</span>", evolve: "Vullaby (Lvl 54)" },
  { id: "285", name: "Skorupi", img: "skorupi.gif", type1: "Poison", type2: "Dark", location: "Motostoke Riverbank<span class='emoji-highlight'>🪟☔</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "286", name: "Drapion", img: "drapion.gif", type1: "Poison", type2: "Dark", location: "Lake of Outrage<span class='emoji-highlight'>⛅</span><span class='encounter-highlight'>👁️</span>", evolve: "Skorupi (Lvl 40)" },
  { id: "287", name: "Litwick", img: "litwick.gif", type1: "Ghost", type2: "Fire", location: "Bridge Field<span class='emoji-highlight'>☀️🌫️</span><span class='encounter-highlight'>🔍</span>", evolve: "" },
  { id: "288", name: "Lampent", img: "lampent.gif", type1: "Ghost", type2: "Fire", location: "Lake of Outrage<span class='emoji-highlight'>☀️</span><span class='encounter-highlight'>👁️</span> <span class='percent'>14%</span>", evolve: "Litwick (Lvl 41)" },
  { id: "289", name: "Chandelure", img: "chandelure.gif", type1: "Ghost", type2: "Fire", location: "Lake of Outrage<span class='emoji-highlight'>☀️</span><span class='encounter-highlight'>📍</span>", evolve: "Lampent (Dusk Stone)" },
  { id: "290", name: "Inkay", img: "inkay.gif", type1: "Dark", type2: "Psychic", location: "Dusty Bowl<span class='encounter-highlight'>🌊</span>", evolve: "" },
  { id: "291", name: "Malamar", img: "malamar.gif", type1: "Dark", type2: "Psychic", location: "Evolve or Trade", evolve: "Inkay (Lvl 30 Holding Console Upside Down)" },
  { id: "292", name: "Sneasel", img: "sneasel.gif", type1: "Dark", type2: "Ice", location: "Motostoke Riverbank<span class='emoji-highlight'>❄️🌨️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "293", name: "Weavile", img: "weavile.gif", type1: "Dark", type2: "Ice", location: "Bridge Field<span class='emoji-highlight'>🌨️</span><span class='encounter-highlight'>📍</span>", evolve: "Sneasel (Level Up w/ Razor Claw at Night)" },
  { id: "294", name: "Sableye", img: "sableye.gif", type1: "Dark", type2: "Ghost", location: "Dusty Bowl<span class='emoji-highlight'>🌫️ </span><span class='encounter-highlight'>👁️</span><span class='shield-highlight'>🛡️only</span>", evolve: "" },
  { id: "295", name: "Mawile", img: "mawile.gif", type1: "Steel", type2: "Fairy", location: "Dusty Bowl<span class='emoji-highlight'>🌨️ </span><span class='encounter-highlight'>👁️</span><span class='sword-highlight'>🗡️only</span>", evolve: "" },
  { id: "296", name: "Maractus", img: "maractus.gif", type1: "Grass", type2: "", location: "Stony Wilderness<span class='emoji-highlight'>☀️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "297", name: "Sigilyph", img: "sigilyph.gif", type1: "Psychic", type2: "", location: "Stony Wilderness<span class='emoji-highlight'>🪟</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "298", name: "Riolu", img: "riolu.gif", type1: "Fighting", type2: "", location: "Giant's Cap<span class='emoji-highlight'>🌨️</span><span class='encounter-highlight'>👁️</span> <span class='percent'>5%</span>", evolve: "" },
  { id: "299", name: "Lucario", img: "lucario.gif", type1: "Fighting", type2: "Steel", location: "North Lake Miloch<span class='emoji-highlight'>🪟</span><span class='encounter-highlight'>📍</span>", evolve: "Riolu (High Friendship at Day)" },
  { id: "300", name: "Torkoal", img: "torkoal.gif", type1: "Fire", type2: "", location: "Motostoke Riverbank<span class='emoji-highlight'>☀️</span><span class='encounter-highlight'>👁️</span> <span class='percent'>10%</span>", evolve: "" },
  { id: "301", name: "Mimikyu", img: "mimikyu.gif", type1: "Ghost", type2: "Fairy", location: "Bridge Field<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>📍</span> <span class='percent'>3%</span>", evolve: "" },
  { id: "302", name: "Cufant", img: "cufant.gif", type1: "Steel", type2: "", location: "Bridge Field<span class='emoji-highlight'>🌨️</span><span class='encounter-highlight'>👁️</span> <span class='percent'>10%</span>", evolve: "" },
  { id: "303", name: "Copperajah", img: "copperajah.gif", type1: "Steel", type2: "", location: "Hammerlocke Hills<span class='encounter-highlight'>📍</span>", evolve: "Cufant (Lvl 34)" },
  { id: "304", name: "Qwilfish", img: "qwilfish.gif", type1: "Water", type2: "Poison", location: "Bridge Field<span class='encounter-highlight'>🌊</span>", evolve: "" },
  { id: "305", name: "Frillish", img: "frillish.gif", type1: "Water", type2: "Ghost", location: "West Lake Axewell<span class='emoji-highlight'>🪟☔</span><span class='encounter-highlight'>🌊</span>", evolve: "" },
  { id: "306", name: "Jellicent", img: "jellicent.gif", type1: "Water", type2: "Ghost", location: "Route 9<span class='encounter-highlight'>👁️🌊</span> <span class='percent'>5%</span>", evolve: "Frillish (Lvl 40)" },
  { id: "307", name: "Mareanie", img: "mareanie.gif", type1: "Poison", type2: "Water", location: "Route 9<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "308", name: "Toxapex", img: "toxapex.gif", type1: "Poison", type2: "Water", location: "Route 9<span class='encounter-highlight'>👁️</span>", evolve: "Mareanie (Lvl 38)" },
  { id: "309", name: "Cramorant", img: "cramorant.gif", type1: "Flying", type2: "Water", location: "Axew's Eye<span class='encounter-highlight'>📍</span>", evolve: "" },
  { id: "310", name: "Toxel", img: "toxel.gif", type1: "Electric", type2: "Poison", location: "Bridge Field<span class='emoji-highlight'>☔</span><span class='encounter-highlight'>👁️</span> <span class='percent'>15%</span>", evolve: "" },
  { id: "311", name: "Toxtricity", img: "toxtricity.gif", type1: "Electric", type2: "Poison", location: "Evolve or Trade", evolve: "Toxel (Lvl 30)" },
  { id: "312", name: "Silicobra", img: "silicobra.gif", type1: "Ground", type2: "", location: "Route 6<span class='encounter-highlight'>🔍</span>", evolve: "" },
  { id: "313", name: "Sandaconda", img: "sandaconda.gif", type1: "Ground", type2: "", location: "Dusty Bowl<span class='encounter-highlight'>📍</span>", evolve: "Silicobra (Lvl 36)" },
  { id: "314", name: "Hippopotas", img: "hippopotas.gif", type1: "Ground", type2: "", location: "Dusty Bowl<span class='emoji-highlight'>☀️🌪️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "315", name: "Hippowdon", img: "hippowdon.gif", type1: "Ground", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>🌪️</span><span class='encounter-highlight'>🔍</span>", evolve: "Hippopotas (Lvl 34)" },
  { id: "316", name: "Durant", img: "durant.gif", type1: "Bug", type2: "Steel", location: "Giant's Mirror<span class='emoji-highlight'>☀️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "317", name: "Heatmor", img: "heatmor.gif", type1: "Fire", type2: "", location: "Giant's Mirror<span class='emoji-highlight'>☀️</span><span class='encounter-highlight'>👁️</span> <span class='percent'>5%</span>", evolve: "" },
  { id: "318", name: "Helioptile", img: "helioptile.gif", type1: "Electric", type2: "Normal", location: "Route 6<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "319", name: "Heliolisk", img: "heliolisk.gif", type1: "Electric", type2: "Normal", location: "Evolve or Trade", evolve: "Helioptile (Sun Stone)" },
  { id: "320", name: "Hawlucha", img: "hawlucha.gif", type1: "Fighting", type2: "Flying", location: "Hammerlocke Hills<span class='encounter-highlight'>📍</span>", evolve: "" },
  { id: "321", name: "Trapinch", img: "trapinch.gif", type1: "Ground", type2: "", location: "Route 6<span class='encounter-highlight'>👁️</span><span class='sword-highlight'>🗡️1%</span><span class='shield-highlight'>🛡️5%</span>", evolve: "" },
  { id: "322", name: "Vibrava", img: "vibrava.gif", type1: "Ground", type2: "Dragon", location: "Evolve or Trade", evolve: "Trapinch (Lvl 35)" },
  { id: "323", name: "Flygon", img: "flygon.gif", type1: "Ground", type2: "Dragon", location: "Dusty Bowl<span class='emoji-highlight'>🪟🌪️</span><span class='encounter-highlight'>📍</span>", evolve: "Vibrava (Lvl 45)" },
  { id: "324", name: "Axew", img: "axew.gif", type1: "Dragon", type2: "", location: "Axew's Eye<span class='emoji-highlight'>🪟⛅☔🌫️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "325", name: "Fraxure", img: "fraxure.gif", type1: "Dragon", type2: "", location: "Evolve or Trade", evolve: "Axew (Lvl 38)" },
  { id: "326", name: "Haxorus", img: "haxorus.gif", type1: "Dragon", type2: "", location: "Axew's Eye<span class='encounter-highlight'>📍</span>", evolve: "Fraxure (Lvl 48)" },
  { id: "327", name: "Yamask", img: "yamask.gif", type1: "Ghost", type2: "", location: "Trade for Galarian Yamask in Fairy Gym", evolve: "" },
  { id: "327g", name: "Galarian Yamask", img: "yamask-galar.gif", type1: "Ghost", type2: "Ground", location: "Route 6<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "328", name: "Runerigus", img: "runerigus.gif", type1: "Ghost", type2: "Ground", location: "Evolve or Trade", evolve: "Galarian Yamask (Look Up Instructions)" },
  { id: "329", name: "Cofagrigus", img: "cofagrigus.gif", type1: "Ghost", type2: "", location: "Evolve or Trade", evolve: "Yamask (Lvl 34)" },
  { id: "330", name: "Honedge", img: "honedge.gif", type1: "Steel", type2: "Ghost", location: "Hammerlocke Hills<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "331", name: "Doublade", img: "doublade.gif", type1: "Steel", type2: "Ghost", location: "Giant's Cap<span class='encounter-highlight'>📍</span>", evolve: "Honedge (Lvl 35)" },
  { id: "332", name: "Aegislash", img: "aegislash.gif", type1: "Steel", type2: "Ghost", location: "Giant's Cap<span class='emoji-highlight'>🌫️ </span><span class='encounter-highlight'>📍</span>", evolve: "Doublade (Dusk Stone)" },
  { id: "333g", name: "Galarian Ponyta", img: "ponyta-galar.gif", type1: "Psychic", type2: "", location: "Glimwood Tangle<span class='encounter-highlight'>🔍</span> <span class='percent'>10%</span><span class='shield-highlight'>🛡️only</span>", evolve: "" },
  { id: "334g", name: "Galarian Rapidash", img: "rapidash-galar.gif", type1: "Psychic", type2: "Fairy", location: "Evolve or Trade", evolve: "Galarian Ponyta (Lvl 40)" },
  { id: "335", name: "Sinistea", img: "sinistea.gif", type1: "Ghost", type2: "", location: "Glimwood Tangle<span class='shield-highlight'>🛡️10%</span><span class='sword-highlight'>🗡️1%</span>", evolve: "" },
  { id: "336", name: "Polteageist", img: "polteageist.gif", type1: "Ghost", type2: "", location: "Evolve or Trade", evolve: "Sinistea (Cracked Pot)" },
  { id: "337", name: "Indeedee", img: "indeedee.gif", type1: "Psychic", type2: "Normal", location: "Lake of Outrage<span class='emoji-highlight'>🌫️</span> <span class='percent'>14%</span>", evolve: "" },
  { id: "338", name: "Phantump", img: "phantump.gif", type1: "Ghost", type2: "Grass", location: "Glimwood Tangle<span class='encounter-highlight'>🔍</span> <span class='percent'>10%</span>", evolve: "" },
  { id: "339", name: "Trevenant", img: "trevenant.gif", type1: "Ghost", type2: "Grass", location: "Evolve or Trade", evolve: "Phantump (Trade)" },
  { id: "340", name: "Morelull", img: "morelull.gif", type1: "Grass", type2: "Fairy", location: "Hammerlocke Hills<span class='emoji-highlight'>🌫️</span><span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "341", name: "Shiinotic", img: "shiinotic.gif", type1: "Grass", type2: "Fairy", location: "Lake of Outrage<span class='emoji-highlight'>⛅☔⚡</span><span class='encounter-highlight'>📍</span>", evolve: "Morelull (Lvl 24)" },
  { id: "342", name: "Oranguru", img: "oranguru.gif", type1: "Normal", type2: "Psychic", location: "Glimwood Tangle<span class='encounter-highlight'>🔍</span> <span class='percent'>4%</span><span class='shield-highlight'>🛡️only</span>", evolve: "" },
  { id: "343", name: "Passimian", img: "passimian.gif", type1: "Fighting", type2: "", location: "Glimwood Tangle<span class='encounter-highlight'>🔍</span> <span class='percent'>4%</span><span class='sword-highlight'>🗡️only</span>", evolve: "" },
  { id: "344", name: "Morpeko", img: "morpeko.gif", type1: "Electric", type2: "Dark", location: "Route 7<span class='encounter-highlight'>👁️</span> <span class='percent'>5%</span>", evolve: "" },
  { id: "345", name: "Falinks", img: "falinks.gif", type1: "Fighting", type2: "", location: "Route 8<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "346", name: "Drampa", img: "drampa.gif", type1: "Normal", type2: "Dragon", location: "Lake of Outrage<span class='emoji-highlight'>⚡</span><span class='encounter-highlight'>🔍</span> <span class='percent'>2%</span><span class='shield-highlight'>🛡️only</span>", evolve: "" },
  { id: "347", name: "Turtonator", img: "turtonator.gif", type1: "Fire", type2: "Dragon", location: "Lake of Outrage<span class='emoji-highlight'>☀️</span><span class='encounter-highlight'>🔍</span> <span class='percent'>2%</span><span class='sword-highlight'>🗡️only</span>", evolve: "" },
  { id: "348", name: "Togedemaru", img: "togedemaru.gif", type1: "Electric", type2: "Steel", location: "Lake of Outrage<span class='emoji-highlight'>🌨️</span> <span class='percent'>13%</span>", evolve: "" },
  { id: "349", name: "Snom", img: "snom.gif", type1: "Ice", type2: "Bug", location: "Route 8<span class='encounter-highlight'>👁️</span> <span class='percent'>5%</span>", evolve: "" },
  { id: "350", name: "Frosmoth", img: "frosmoth.gif", type1: "Ice", type2: "Bug", location: "Evolve or Trade", evolve: "Snom (High Friendship at Night)" },
  { id: "351", name: "Clobbopus", img: "clobbopus.gif", type1: "Fighting", type2: "", location: "Route 9<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "352", name: "Grapploct", img: "grapploct.gif", type1: "Fighting", type2: "", location: "Lake of Outrage<span class='encounter-highlight'>📍</span>", evolve: "Clobbopus (Lvl Up w/ Taunt)" },
  { id: "353", name: "Pincurchin", img: "pincurchin.gif", type1: "Electric", type2: "", location: "Route 9<span class='encounter-highlight'>🔍</span> <span class='percent'>5%</span>", evolve: "" },
  { id: "354", name: "Mantyke", img: "mantyke.gif", type1: "Water", type2: "Flying", location: "Lake of Outrage<span class='encounter-highlight'>🌊</span>", evolve: "" },
  { id: "355", name: "Mantine", img: "mantine.gif", type1: "Water", type2: "Flying", location: "Lake of Outrage<span class='encounter-highlight'>🌊</span>", evolve: "Mantyke (Level up w/ Remoraid in Party)" },
  { id: "356", name: "Wailmer", img: "wailmer.gif", type1: "Water", type2: "", location: "Route 9<span class='encounter-highlight'>🌊</span>", evolve: "" },
  { id: "357", name: "Wailord", img: "wailord.gif", type1: "Water", type2: "", location: "Route 9<span class='encounter-highlight'>🎣</span> <span class='percent'>5%</span>", evolve: "Wailmer (Lvl 40)" },
  { id: "358", name: "Bergmite", img: "bergmite.gif", type1: "Ice", type2: "", location: "Route 9<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "359", name: "Avalugg", img: "avalugg.gif", type1: "Ice", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>❄️🌨️</span><span class='encounter-highlight'>📍</span>", evolve: "Bergmite (Lvl 37)" },
  { id: "360", name: "Dhelmise", img: "dhelmise.gif", type1: "Ghost", type2: "Grass", location: "Route 9<span class='encounter-highlight'>👁️</span> <span class='percent'>1%</span>", evolve: "" },
  { id: "361", name: "Lapras", img: "lapras.gif", type1: "Water", type2: "Ice", location: "Lake of Outrage<span class='encounter-highlight'>🌊</span>", evolve: "" },
  { id: "362", name: "Lunatone", img: "lunatone.gif", type1: "Rock", type2: "Psychic", location: "Giant's Cap<span class='encounter-highlight'>👁️</span><span class='shield-highlight'>🛡️only</span>", evolve: "" },
  { id: "363", name: "Solrock", img: "solrock.gif", type1: "Rock", type2: "Psychic", location: "Giant's Cap<span class='encounter-highlight'>👁️</span><span class='sword-highlight'>🗡️only</span>", evolve: "" },
  { id: "364", name: "Mime Jr.", img: "mimejr.gif", type1: "Psychic", type2: "Fairy", location: "Rolling Fields<span class='emoji-highlight'>🌨️</span><span class='encounter-highlight'>📍</span>", evolve: "Breed Mr. Mime holding Odd Incense" },
  { id: "365", name: "Mr. Mime", img: "mrmime.gif", type1: "Psychic", type2: "Fairy", location: "Trade for Obstagoon in Spikemuth", evolve: "" },
  { id: "365g", name: "Galarian Mr. Mime", img: "mrmime-galar.gif", type1: "Psychic", type2: "Ice", location: "Route 10<span class='encounter-highlight'>👁️</span>", evolve: "" },
  { id: "366", name: "Mr. Rime", img: "mrrime.gif", type1: "Psychic", type2: "Ice", location: "Evolve or Trade", evolve: "Galarian Mr. Mime (Lvl 42)" },
  { id: "367g", name: "Galarian Darumaka", img: "darumaka-galar.gif", type1: "Ice", type2: "", location: "Route 10<span class='encounter-highlight'>🔍</span> <span class='percent'>5%</span><span class='sword-highlight'>🗡️only</span>", evolve: "" },
  { id: "368g", name: "Galarian Darmanitan", img: "darmanitan-galar.gif", type1: "Ice", type2: "", location: "Evolve or Trade", evolve: "Galarian Darumaka (Ice Stone)" },
  { id: "369", name: "Stonjourner", img: "stonjourner.gif", type1: "Rock", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>🌪️</span><span class='encounter-highlight'>🔍</span> <span class='percent'>5%</span><span class='sword-highlight'>🗡️only</span>", evolve: "" },
  { id: "370", name: "Eiscue", img: "eiscue.gif", type1: "Ice", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>🌨️</span><span class='encounter-highlight'>🔍</span> <span class='percent'>5%</span><span class='shield-highlight'>🛡️only</span>", evolve: "" },
  { id: "371", name: "Duraludon", img: "duraludon.gif", type1: "Steel", type2: "Dragon", location: "Giant's Seat<span class='encounter-highlight'>📍</span>", evolve: "" },
  { id: "372", name: "Rotom", img: "rotom.gif", type1: "Electric", type2: "Ghost", location: "Lake of Outrage<span class='emoji-highlight'>☔⚡ </span><span class='encounter-highlight'>👁️</span> <span class='percent'>2%</span>", evolve: "" },
  { id: "373", name: "Ditto", img: "ditto.gif", type1: "Normal", type2: "", location: "Lake of Outrage<span class='encounter-highlight'>👁️</span> <span class='percent'>10%</span>", evolve: "" },
  { id: "374", name: "Dracozolt", img: "dracozolt.gif", type1: "Electric", type2: "Dragon", location: "2 Fossilized Bird + 2 Fossilized Drake", evolve: "" },
  { id: "375", name: "Arctozolt", img: "arctozolt.gif", type1: "Electric", type2: "Ice", location: "2 Fossilized Bird + 2 Fossilized Dino", evolve: "" },
  { id: "376", name: "Dracovish", img: "dracovish.gif", type1: "Water", type2: "Dragon", location: "2 Fossilized Fish + 2 Fossilized Drake", evolve: "" },
  { id: "377", name: "Arctovish", img: "arctovish.gif", type1: "Water", type2: "Ice", location: "2 Fossilized Fish + 2 Fossilized Dino", evolve: "" },
  { id: "378", name: "Charmander", img: "charmander.gif", type1: "Fire", type2: "", location: "Hop's House", evolve: "" },
  { id: "379", name: "Charmeleon", img: "charmeleon.gif", type1: "Fire", type2: "", location: "Evolve or Trade", evolve: "Charmander (Lvl 16)" },
  { id: "380", name: "Charizard", img: "charizard.gif", type1: "Fire", type2: "Flying", location: "Evolve or Trade", evolve: "Charmeleon (Lvl 36)" },
  { id: "381", name: "Type Null", img: "type-null.gif", type1: "Normal", type2: "", location: "Battle Tower", evolve: "" },
  { id: "382", name: "Silvally", img: "silvally.gif", type1: "Normal", type2: "", location: "Evolve or Trade", evolve: "Type: Null (High Friendship)" },
  { id: "383", name: "Larvitar", img: "larvitar.gif", type1: "Rock", type2: "Ground", location: "Lake of Outrage<span class='emoji-highlight'>⛅☀️</span><span class='encounter-highlight'>🔍</span> <span class='percent'>5%</span><span class='shield-highlight'>🛡️only</span>", evolve: "" },
  { id: "384", name: "Pupitar", img: "pupitar.gif", type1: "Rock", type2: "Ground", location: "Lake of Outrage<span class='emoji-highlight'>🌪️</span><span class='encounter-highlight'>👁️</span> <span class='percent'>2%</span><span class='shield-highlight'>🛡️only</span>", evolve: "Larvitar (Lvl 30)" },
  { id: "385", name: "Tyranitar", img: "tyranitar.gif", type1: "Rock", type2: "Dark", location: "Dusty Bowl<span class='emoji-highlight'>🪟❄️🌨️🌪️</span><span class='encounter-highlight'>📍</span><span class='shield-highlight'>🛡️only</span>", evolve: "Pupitar (Lvl 55)" },
  { id: "386", name: "Deino", img: "deino.gif", type1: "Dark", type2: "Dragon", location: "Lake of Outrage<span class='emoji-highlight'>☔</span> <span class='percent'>2%</span><span class='sword-highlight'>🗡️only</span>", evolve: "" },
  { id: "387", name: "Zweilous", img: "zweilous.gif", type1: "Dark", type2: "Dragon", location: "Lake of Outrage<span class='emoji-highlight'>🌪️</span><span class='encounter-highlight'>👁️</span> <span class='percent'>2%</span><span class='sword-highlight'>🗡️only</span>", evolve: "Deino (Lvl 50)" },
  { id: "388", name: "Hydreigon", img: "hydreigon.gif", type1: "Dark", type2: "Dragon", location: "Evolve or Trade", evolve: "Zweilous (Lvl 64)" },
  { id: "389", name: "Goomy", img: "goomy.gif", type1: "Dragon", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>☔</span><span class='encounter-highlight'>🔍</span> <span class='percent'>2%</span><span class='shield-highlight'>🛡️only</span>", evolve: "" },
  { id: "390", name: "Sliggoo", img: "sliggoo.gif", type1: "Dragon", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>⚡</span><span class='encounter-highlight'>🔍</span> <span class='percent'>2%</span><span class='shield-highlight'>🛡️only</span>", evolve: "Goomy (Lvl 40)" },
  { id: "391", name: "Goodra", img: "goodra.gif", type1: "Dragon", type2: "", location: "Evolve or Trade", evolve: "Sliggoo (Lvl 50 while raining)" },
  { id: "392", name: "Jangmo-o", img: "jangmo-o.gif", type1: "Dragon", type2: "", location: "Lake of Outrage<span class='emoji-highlight'>⛅☀️</span><span class='encounter-highlight'>🔍</span> <span class='percent'>5%</span><span class='sword-highlight'>🗡️only</span>", evolve: "" },
  { id: "393", name: "Hakamo-o", img: "hakamo-o.gif", type1: "Dragon", type2: "Fighting", location: "Lake of Outrage<span class='emoji-highlight'>⚡</span><span class='encounter-highlight'>🔍</span> <span class='percent'>2%</span><span class='sword-highlight'>🗡️only</span>", evolve: "Jangmo-o (Lvl 35)" },
  { id: "394", name: "Kommo-o", img: "kommo-o.gif", type1: "Dragon", type2: "Fighting", location: "Dusty Bowl<span class='emoji-highlight'>🪟☀️❄️🌪️</span><span class='encounter-highlight'>📍</span><span class='sword-highlight'>🗡️only</span>", evolve: "Hakamo-o (Lvl 45)" },
  { id: "395", name: "Dreepy", img: "dreepy.gif", type1: "Dragon", type2: "Ghost", location: "Lake of Outrage<span class='emoji-highlight'>⚡🌫️</span><span class='encounter-highlight'>🔍</span> <span class='percent'>2%</span>", evolve: "" },
  { id: "396", name: "Drakloak", img: "drakloak.gif", type1: "Dragon", type2: "Ghost", location: "Lake of Outrage<span class='emoji-highlight'>⚡🌫️</span><span class='encounter-highlight'>👁️</span> <span class='percent'>2%</span>", evolve: "Dreepy (Lvl 50)" },
  { id: "397", name: "Dragapult", img: "dragapult.gif", type1: "Dragon", type2: "Ghost", location: "Evolve or Trade", evolve: "Drakloak (Lvl 60)" },
  { id: "398", name: "Zacian", img: "zacian.gif", type1: "Fairy", type2: "Steel", location: "Energy Plant<span class='sword-highlight'>🗡️only</span>", evolve: "" },
  { id: "399", name: "Zamazenta", img: "zamazenta.gif", type1: "Fighting", type2: "Steel", location: "Energy Plant<span class='shield-highlight'>🛡️only</span>", evolve: "" },
  { id: "400", name: "Eternatus", img: "eternatus.gif", type1: "Poison", type2: "Dragon", location: "Energy Plant", evolve: "" },
];
